/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.epn.trappi.gui.proveedores;

import com.epn.trappi.db.proveedores.ProveedoresDb;
import com.epn.trappi.models.proveedores.Bien;
import com.epn.trappi.models.proveedores.Compra;
import com.epn.trappi.models.proveedores.CompraDeProducto;
import com.epn.trappi.models.proveedores.Inventario;
import com.epn.trappi.models.proveedores.ListaDeBienes;
import com.epn.trappi.models.proveedores.ListaDeCompras;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author franc
 */
public class guiFormularioComprasPanel extends javax.swing.JPanel {

    /**
     * Creates new form guiFormularioComprasPanel
     */
    DefaultTableModel modelo;
    private final ProveedoresDb db = new ProveedoresDb();
    private JPanel verTodo;
    
    private ListaDeBienes listaDeProductos;
    public int[][] seleccionados;
    private ListaDeCompras solicitud;

    
    public guiFormularioComprasPanel(JPanel verTodo) {
        initComponents();
        this.verTodo=verTodo;
        cargar();
        jCheckBoxAñadir.setEnabled(false);
        jBotonSol.setEnabled(false);
        jTextFieldCantidad.setEnabled(false);
    }
    
    public void cargar(){
        int auxiliarTamañoBuffer=0;
        String[] titulos = {"Producto","Precio unitario","Proveedor"};
        String[] fila = new String [3];
        modelo = new DefaultTableModel(null, titulos);
        listaDeProductos=new ListaDeBienes((ArrayList)db.getProductos());
        for (Bien producto : listaDeProductos.getListaBienes()) {
            fila[0]= producto.getNombre();
            fila[1]= ""+producto.getPrecio();
            fila[2]= producto.getProveeedor().getRazonSocial();
            modelo.addRow(fila);
            auxiliarTamañoBuffer++;
        }
        jTable1.setModel(modelo);
        iniciarBufferSeleccionar(auxiliarTamañoBuffer);
    }
    
    public void iniciarBufferSeleccionar(int auxiliarTamañoBuffer){
        seleccionados = new int[auxiliarTamañoBuffer][2];
        for(int i =0; i<auxiliarTamañoBuffer;i++){
            seleccionados[i][0]=0;
            seleccionados[i][1]=0;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVerTodos = new javax.swing.JPanel();
        jBotonSol = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFechCompNotaCred = new javax.swing.JTextField();
        jButRegFactCompNotaCred1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jCheckBoxAñadir = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        PanelVerTodos.setBackground(new java.awt.Color(255, 255, 255));

        jBotonSol.setBackground(new java.awt.Color(38, 112, 171));
        jBotonSol.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBotonSol.setForeground(new java.awt.Color(240, 240, 241));
        jBotonSol.setText("Generar solicitud de compra");
        jBotonSol.setBorderPainted(false);
        jBotonSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonSolActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Buscar Producto");

        jTextFechCompNotaCred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFechCompNotaCredActionPerformed(evt);
            }
        });
        jTextFechCompNotaCred.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFechCompNotaCredKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFechCompNotaCredKeyTyped(evt);
            }
        });

        jButRegFactCompNotaCred1.setBackground(new java.awt.Color(38, 112, 171));
        jButRegFactCompNotaCred1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButRegFactCompNotaCred1.setForeground(new java.awt.Color(240, 240, 241));
        jButRegFactCompNotaCred1.setText("Buscar");
        jButRegFactCompNotaCred1.setBorderPainted(false);
        jButRegFactCompNotaCred1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegFactCompNotaCred1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Añadir");

        jCheckBoxAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxAñadirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCheckBoxAñadirMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Ingresar Cantidad");

        jTextFieldCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel10)
                .addGap(33, 33, 33)
                .addComponent(jCheckBoxAñadir)
                .addGap(42, 42, 42)
                .addComponent(jLabel11)
                .addGap(26, 26, 26)
                .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jCheckBoxAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout PanelVerTodosLayout = new javax.swing.GroupLayout(PanelVerTodos);
        PanelVerTodos.setLayout(PanelVerTodosLayout);
        PanelVerTodosLayout.setHorizontalGroup(
            PanelVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVerTodosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBotonSol)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelVerTodosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PanelVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(PanelVerTodosLayout.createSequentialGroup()
                        .addComponent(jTextFechCompNotaCred, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButRegFactCompNotaCred1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelVerTodosLayout.setVerticalGroup(
            PanelVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVerTodosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addGroup(PanelVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFechCompNotaCred, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButRegFactCompNotaCred1))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jBotonSol)
                .addGap(23, 23, 23))
        );

        add(PanelVerTodos);
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonSolActionPerformed
        try {
            Inventario inventario=new Inventario();
            solicitud = new ListaDeCompras(new ArrayList<Compra>());
            String auxiliarRuc="";
            for(int i=0;i<seleccionados.length;i++){
                if(seleccionados[i][0]==1){
                    CompraDeProducto compra;
                    ListaDeBienes lista = new ListaDeBienes();
                    auxiliarRuc=listaDeProductos.getListaBienes().get(i).getProveeedor().getRuc();
                    for(int j=0;j<seleccionados.length;j++){
                        if(auxiliarRuc.equals(listaDeProductos.getListaBienes().get(j).getProveeedor().getRuc())){
                            if(seleccionados[j][0]==1){
                                listaDeProductos.getListaBienes().get(j).setCantidad(seleccionados[j][1]);
                                lista.añadirBien(listaDeProductos.getListaBienes().get(j));
                                seleccionados[j][0]=0;
                            }
                        }
                    }
                    compra = new CompraDeProducto(inventario,lista, "Pendiente");
                    solicitud.añadirCompra(compra);
                }
            }
            new CambiaPanel(verTodo, new guiDescripcionCompra(solicitud));
        } catch (IOException ex) {
            Logger.getLogger(guiFormularioComprasPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBotonSolActionPerformed

    private void jTextFechCompNotaCredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFechCompNotaCredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFechCompNotaCredActionPerformed

    private void jTextFechCompNotaCredKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFechCompNotaCredKeyPressed

    }//GEN-LAST:event_jTextFechCompNotaCredKeyPressed

    private void jTextFechCompNotaCredKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFechCompNotaCredKeyTyped

    }//GEN-LAST:event_jTextFechCompNotaCredKeyTyped

    private void jButRegFactCompNotaCred1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegFactCompNotaCred1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButRegFactCompNotaCred1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jTextFieldCantidad.setEnabled(true);
        jBotonSol.setEnabled(true);
        jCheckBoxAñadir.setEnabled(true);
        
        if(seleccionados[jTable1.getSelectedRow()][0]==0){
            jCheckBoxAñadir.setSelected(false);
        }
        else{
            jCheckBoxAñadir.setSelected(true);
        }
        if(seleccionados[jTable1.getSelectedRow()][1]==0){
            jTextFieldCantidad.setText("");
        }
        else{
            jTextFieldCantidad.setText(seleccionados[jTable1.getSelectedRow()][1]+"");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jCheckBoxAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxAñadirMouseClicked
        
    }//GEN-LAST:event_jCheckBoxAñadirMouseClicked

    private void jTextFieldCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadKeyReleased
        int cantidad=Integer.parseInt(jTextFieldCantidad.getText());
        seleccionados[jTable1.getSelectedRow()][1]=cantidad;
        System.out.print(cantidad);
    }//GEN-LAST:event_jTextFieldCantidadKeyReleased

    private void jCheckBoxAñadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxAñadirMouseExited
        if(jCheckBoxAñadir.isSelected())
            seleccionados[jTable1.getSelectedRow()][0]=1;
        else{
            seleccionados[jTable1.getSelectedRow()][0]=0;
        }
    }//GEN-LAST:event_jCheckBoxAñadirMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelVerTodos;
    private javax.swing.JButton jBotonSol;
    private javax.swing.JButton jButRegFactCompNotaCred1;
    private javax.swing.JCheckBox jCheckBoxAñadir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFechCompNotaCred;
    private javax.swing.JTextField jTextFieldCantidad;
    // End of variables declaration//GEN-END:variables
}
