/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.epn.trappi.gui.proveedores;

import com.epn.trappi.db.proveedores.ProveedoresDb;
import com.epn.trappi.models.proveedores.Bien;
import com.epn.trappi.models.proveedores.Compra;
import com.epn.trappi.models.proveedores.CompraDeProducto;
import com.epn.trappi.models.proveedores.Inventario;
import com.epn.trappi.models.proveedores.ListaDeBienes;
import com.epn.trappi.models.proveedores.ListaDeCompras;
import com.epn.trappi.models.proveedores.Producto;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author franc
 */
public class guiFormularioComprasPanel extends javax.swing.JPanel {

    /**
     * Creates new form guiFormularioComprasPanel
     */
    DefaultTableModel modelo;
    private final ProveedoresDb db = new ProveedoresDb();
    private JPanel verTodo;

    private ListaDeBienes listaDeProductos;
    //public int[][] seleccionados;
    private int auxiliarNumeroProductos=0;
    private ListaDeCompras solicitud;
    private ListaDeBienes listaDeProductosSeleccionados=new ListaDeBienes();

    public guiFormularioComprasPanel(JPanel verTodo) {
        initComponents();
        this.verTodo = verTodo;
        listaDeProductos = new ListaDeBienes((ArrayList) db.getProductos());
        cargar();
        jCheckBoxAñadir.setEnabled(false);
        jBotonSol.setEnabled(false);
        jTextFieldCantidad.setEnabled(false);
    }

    public void cargar() {
        //int auxiliarTamañoBuffer = 0;
        listaDeProductos.mostrarLista(jTable1);
        //iniciarBufferSeleccionar(auxiliarTamañoBuffer);
    }

    /*public void iniciarBufferSeleccionar(int auxiliarTamañoBuffer) {
        seleccionados = new int[auxiliarTamañoBuffer][2];
        for (int i = 0; i < auxiliarTamañoBuffer; i++) {
            seleccionados[i][0] = 0;
            seleccionados[i][1] = 0;
        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVerTodos = new javax.swing.JPanel();
        jBotonSol = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jButRegFactCompNotaCred1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jCheckBoxAñadir = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        PanelVerTodos.setBackground(new java.awt.Color(255, 255, 255));

        jBotonSol.setBackground(new java.awt.Color(38, 112, 171));
        jBotonSol.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBotonSol.setForeground(new java.awt.Color(240, 240, 241));
        jBotonSol.setText("Generar solicitud de compra");
        jBotonSol.setBorderPainted(false);
        jBotonSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonSolActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Buscar Producto");

        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });
        txtNombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreProductoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreProductoKeyTyped(evt);
            }
        });

        jButRegFactCompNotaCred1.setBackground(new java.awt.Color(38, 112, 171));
        jButRegFactCompNotaCred1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButRegFactCompNotaCred1.setForeground(new java.awt.Color(240, 240, 241));
        jButRegFactCompNotaCred1.setText("Buscar");
        jButRegFactCompNotaCred1.setBorderPainted(false);
        jButRegFactCompNotaCred1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegFactCompNotaCred1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Añadir");

        jCheckBoxAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCheckBoxAñadirMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Ingresar Cantidad");

        jTextFieldCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addGap(26, 26, 26)
                .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel10)
                .addGap(33, 33, 33)
                .addComponent(jCheckBoxAñadir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jCheckBoxAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelVerTodosLayout = new javax.swing.GroupLayout(PanelVerTodos);
        PanelVerTodos.setLayout(PanelVerTodosLayout);
        PanelVerTodosLayout.setHorizontalGroup(
            PanelVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVerTodosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBotonSol)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelVerTodosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PanelVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(PanelVerTodosLayout.createSequentialGroup()
                        .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButRegFactCompNotaCred1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelVerTodosLayout.setVerticalGroup(
            PanelVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVerTodosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addGroup(PanelVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButRegFactCompNotaCred1))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jBotonSol)
                .addGap(23, 23, 23))
        );

        add(PanelVerTodos);
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonSolActionPerformed
        /*try {
            Inventario inventario = new Inventario();
            solicitud = new ListaDeCompras(new ArrayList<Compra>());
            String auxiliarRuc = "";
            for (int i = 0; i < seleccionados.length; i++) {
                if (seleccionados[i][0] == 1) {
                    CompraDeProducto compra;
                    ListaDeBienes lista = new ListaDeBienes();
                    auxiliarRuc = listaDeProductos.getListaBienes().get(i).getProveeedor().getRuc();
                    for (int j = 0; j < seleccionados.length; j++) {
                        if (auxiliarRuc.equals(listaDeProductos.getListaBienes().get(j).getProveeedor().getRuc())) {
                            if (seleccionados[j][0] == 1) {
                                listaDeProductos.getListaBienes().get(j).setCantidad(seleccionados[j][1]);
                                lista.añadirBien(listaDeProductos.getListaBienes().get(j));
                                seleccionados[j][0] = 0;
                            }
                        }
                    }
                    compra = new CompraDeProducto(inventario, lista, "Pendiente");
                    solicitud.añadirCompra(compra);
                }
            }
            new CambiaPanel(verTodo, new guiDescripcionCompra(solicitud));
        } catch (IOException ex) {
            Logger.getLogger(guiFormularioComprasPanel.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        solicitud = new ListaDeCompras();
        solicitud.añadirCompra(new CompraDeProducto(listaDeProductosSeleccionados, "Pendiente"));
        new CambiaPanel(verTodo, new guiDescripcionCompra(solicitud));
    }//GEN-LAST:event_jBotonSolActionPerformed

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void txtNombreProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProductoKeyPressed

    }//GEN-LAST:event_txtNombreProductoKeyPressed

    private void txtNombreProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProductoKeyTyped
        String producto = txtNombreProducto.getText();
        try {
            if (producto.length() >= 1) {
                listaDeProductos = new ListaDeBienes((ArrayList) db.buscarProductos(producto));
                cargar();
            } else {
                cargar();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Producto no encontrado", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtNombreProductoKeyTyped

    private void jButRegFactCompNotaCred1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegFactCompNotaCred1ActionPerformed
        String producto = txtNombreProducto.getText();
        try {
            if (producto.length() >= 1) {
                listaDeProductos = new ListaDeBienes((ArrayList) db.buscarProductos(producto));
                cargar();
            } else {
                cargar();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Producto no encontrado", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButRegFactCompNotaCred1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jTextFieldCantidad.setEnabled(true);
        jBotonSol.setEnabled(true);
        jCheckBoxAñadir.setEnabled(true);

        if (listaDeProductosSeleccionados.getListaBienes().contains(listaDeProductos.getListaBienes().get(jTable1.getSelectedRow()))){
            jCheckBoxAñadir.setSelected(true);
            jTextFieldCantidad.setText(listaDeProductosSeleccionados.getListaBienes().get(
                    listaDeProductosSeleccionados.getListaBienes().indexOf(
                            listaDeProductos.getListaBienes().get(jTable1.getSelectedRow()))).getCantidad()+"");
        } else {
            jCheckBoxAñadir.setSelected(false);
            jTextFieldCantidad.setText("");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextFieldCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadKeyReleased
        auxiliarNumeroProductos = Integer.parseInt(jTextFieldCantidad.getText());
        System.out.print(auxiliarNumeroProductos);
    }//GEN-LAST:event_jTextFieldCantidadKeyReleased

    private void jCheckBoxAñadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxAñadirMouseExited
        if (jCheckBoxAñadir.isSelected()&&!jTextFieldCantidad.getText().isBlank()){
            listaDeProductosSeleccionados.añadirBien(listaDeProductos.getListaBienes().get(jTable1.getSelectedRow()));
            listaDeProductosSeleccionados.getListaBienes().get(
                    listaDeProductosSeleccionados.getListaBienes().indexOf(
                            listaDeProductos.getListaBienes().get(jTable1.getSelectedRow()))).setCantidad(auxiliarNumeroProductos);
        }
        else {
            jCheckBoxAñadir.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBoxAñadirMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelVerTodos;
    private javax.swing.JButton jBotonSol;
    private javax.swing.JButton jButRegFactCompNotaCred1;
    private javax.swing.JCheckBox jCheckBoxAñadir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField txtNombreProducto;
    // End of variables declaration//GEN-END:variables
}
