/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.epn.trappi.gui.proveedores;

import com.epn.trappi.db.proveedores.ProveedoresDb;
import com.epn.trappi.models.proveedores.Proveedor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Peterca
 */
public class guiListaProveedores extends javax.swing.JPanel {

    DefaultTableModel modelo = new DefaultTableModel();
    boolean clic = false;
    ArrayList<Proveedor> listaP;
    Proveedor proveedorSeleccionado;
    private final ProveedoresDb db = new ProveedoresDb();

    /**
     * Creates new form guiListaProveedores1
     */
    public guiListaProveedores() {
        initComponents();
        listaP = (ArrayList<Proveedor>) db.getProveedores();
        cargarProveedor();
    }

    private void cargarProveedor() {
        String[] titulos = {"Ruc", "Razón Social", "Dirección", "Número de Cuenta"};
        String[] fila = new String[4];
        modelo = new DefaultTableModel(null, titulos);
        for (Proveedor proveedor : listaP) {
            fila[0] = proveedor.getRuc();
            fila[1] = "" + proveedor.getRazonSocial();
            fila[2] = "" + proveedor.getDireccion();
            fila[3] = "" + proveedor.getCuenta();
            modelo.addRow(fila);
        }
        jtbProveedores.setModel(modelo);
    }

    private void mostrarProveedor(String ruc, String razonsocial, String direccion, String cuenta) {
        txtBuscarRUC.setText(ruc);
        txtRazonSocial.setText(razonsocial);
        txtDireccion.setText(direccion);
        txtNCuenta.setText(cuenta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVerTodos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtBuscarRUC = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtRazonSocial = new javax.swing.JTextField();
        txtNCuenta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbProveedores = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        PanelVerTodos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("RUC:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Razón Social:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Dirección:");

        txtBuscarRUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarRUCActionPerformed(evt);
            }
        });
        txtBuscarRUC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarRUCKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarRUCKeyTyped(evt);
            }
        });

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });

        txtRazonSocial.setEnabled(false);
        txtRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazonSocialActionPerformed(evt);
            }
        });
        txtRazonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRazonSocialKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRazonSocialKeyTyped(evt);
            }
        });

        txtNCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNCuentaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNCuentaKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Número de Cuenta:");

        btnActualizar.setBackground(new java.awt.Color(38, 112, 171));
        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(240, 240, 241));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorderPainted(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(38, 112, 171));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(240, 240, 241));
        btnBuscar.setBorderPainted(false);
        btnBuscar.setLabel("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jtbProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ruc", "Razón Social", "Dirección", "Número de Cuenta"
            }
        ));
        jtbProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbProveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbProveedores);

        btnEliminar.setBackground(new java.awt.Color(38, 112, 171));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(240, 240, 241));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelVerTodosLayout = new javax.swing.GroupLayout(PanelVerTodos);
        PanelVerTodos.setLayout(PanelVerTodosLayout);
        PanelVerTodosLayout.setHorizontalGroup(
            PanelVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVerTodosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVerTodosLayout.createSequentialGroup()
                        .addGroup(PanelVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVerTodosLayout.createSequentialGroup()
                        .addComponent(txtBuscarRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(PanelVerTodosLayout.createSequentialGroup()
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVerTodosLayout.createSequentialGroup()
                        .addGroup(PanelVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNCuenta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRazonSocial, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        PanelVerTodosLayout.setVerticalGroup(
            PanelVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVerTodosLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addGroup(PanelVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelVerTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addContainerGap())
        );

        add(PanelVerTodos);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarRUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarRUCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarRUCActionPerformed

    private void txtBuscarRUCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarRUCKeyPressed

    }//GEN-LAST:event_txtBuscarRUCKeyPressed

    private void txtBuscarRUCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarRUCKeyTyped
        // Busqueda
        // Atributos
        String ruc = txtBuscarRUC.getText();
        if (ruc.length() >= 1) {
            listaP = (ArrayList<Proveedor>) db.buscarProveedores(ruc);
            cargarProveedor();
        }
    }//GEN-LAST:event_txtBuscarRUCKeyTyped

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyPressed

    }//GEN-LAST:event_txtDireccionKeyPressed

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped

    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtRazonSocialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonSocialKeyPressed

    }//GEN-LAST:event_txtRazonSocialKeyPressed

    private void txtRazonSocialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonSocialKeyTyped

    }//GEN-LAST:event_txtRazonSocialKeyTyped

    private void txtNCuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNCuentaKeyPressed

    }//GEN-LAST:event_txtNCuentaKeyPressed

    private void txtNCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNCuentaKeyTyped

    }//GEN-LAST:event_txtNCuentaKeyTyped

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // Atributos
        String ruc;
        String direccion;
        String cuenta;

        ruc = txtBuscarRUC.getText();
        direccion = txtDireccion.getText();
        cuenta = txtNCuenta.getText();

        if (guiProveedores.validarDireccion(direccion)) {
            if (cuenta.length() == 10) {
                try {
                    db.actualizarProveedor(ruc, direccion, cuenta);
                    JOptionPane.showMessageDialog(null, "Proveedor Actualizado.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "No se pudo Actualizar el Proveedor", "Error", JOptionPane.INFORMATION_MESSAGE);
                }
                listaP = (ArrayList<Proveedor>) db.getProveedores();
                cargarProveedor();
                
                vaciarCampos();

            } else {
                JOptionPane.showMessageDialog(null, "Número de Cuenta Incorrecta");
                this.vaciarCampos();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Dirección Incorrecta");
            this.vaciarCampos();
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    public void vaciarCampos() {
        txtDireccion.setText("");
        txtNCuenta.setText("");
        txtRazonSocial.setText("");
        txtBuscarRUC.setText("");
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
//         TODO add your handling code here:
        // Atributos
        String ruc = txtBuscarRUC.getText();
        try {
            if (ruc.length() >= 1) {
                listaP = (ArrayList<Proveedor>) db.buscarProveedores(ruc);
                cargarProveedor();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Proveedor no encontrado", "Error", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed


    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        Object[] o = {"Confirmar", "Cancelar"};
        int c = 0;
        c = JOptionPane.showOptionDialog(null, "¿Está seguro de eliminar al proveedor?", "Eliminar un Proveedor", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, o, o[0]);
        if (c == 0) {
            int fila = jtbProveedores.getSelectedRow();
            modelo.removeRow(fila);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jtbProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbProveedoresMouseClicked
        // TODO add your handling code here:
        int row = jtbProveedores.rowAtPoint(evt.getPoint());
        int col = jtbProveedores.columnAtPoint(evt.getPoint());
        if (row >= 0 && col >= 0) {
            mostrarProveedor(modelo.getValueAt(row, 0).toString(), modelo.getValueAt(row, 1).toString(), modelo.getValueAt(row, 2).toString(), modelo.getValueAt(row, 3).toString());
        }
    }//GEN-LAST:event_jtbProveedoresMouseClicked

    private void txtRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazonSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazonSocialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelVerTodos;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbProveedores;
    private javax.swing.JTextField txtBuscarRUC;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNCuenta;
    private javax.swing.JTextField txtRazonSocial;
    // End of variables declaration//GEN-END:variables
}
