/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.epn.trappi.gui.proveedores;

/**
 *
 * @author David Morales
 */
public class Menu_Trappi extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Trappi
     */
    public Menu_Trappi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVerTodos = new javax.swing.JPanel();
        jIVA = new javax.swing.JLabel();
        jValor = new javax.swing.JLabel();
        jPEncabezado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLSidimLogo = new javax.swing.JLabel();
        jPMod = new javax.swing.JPanel();
        jPanOpcionesDeclaracion = new javax.swing.JPanel();
        jButCompras = new javax.swing.JButton();
        jPanOpcInventario = new javax.swing.JPanel();
        jPanOpcProveedores = new javax.swing.JPanel();
        jPanOpcProductos = new javax.swing.JPanel();
        jButInventario = new javax.swing.JButton();
        jButDashboard = new javax.swing.JButton();
        jPanOpcServicios = new javax.swing.JPanel();
        jButCompra = new javax.swing.JButton();
        jPanOpcCompras = new javax.swing.JPanel();
        jtbCerrarSesion = new javax.swing.JButton();
        jLabNombreContribuyente1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelVerTodos.setBackground(new java.awt.Color(255, 255, 255));
        PanelVerTodos.setLayout(new javax.swing.BoxLayout(PanelVerTodos, javax.swing.BoxLayout.LINE_AXIS));

        jIVA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PanelVerTodos.add(jIVA);

        jValor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PanelVerTodos.add(jValor);

        jPEncabezado.setBackground(new java.awt.Color(61, 57, 57));

        jLabel2.setBackground(new java.awt.Color(80, 125, 180));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 241));
        jLabel2.setText("Bienvenido: Administrador  1");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPEncabezadoLayout = new javax.swing.GroupLayout(jPEncabezado);
        jPEncabezado.setLayout(jPEncabezadoLayout);
        jPEncabezadoLayout.setHorizontalGroup(
            jPEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEncabezadoLayout.createSequentialGroup()
                .addComponent(jLSidimLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(23, 23, 23))
        );
        jPEncabezadoLayout.setVerticalGroup(
            jPEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLSidimLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPMod.setBackground(new java.awt.Color(51, 51, 51));
        jPMod.setForeground(new java.awt.Color(51, 51, 51));
        jPMod.setMaximumSize(new java.awt.Dimension(300, 200));
        jPMod.setPreferredSize(new java.awt.Dimension(300, 280));

        jPanOpcionesDeclaracion.setBackground(new java.awt.Color(51, 51, 51));

        jButCompras.setBackground(new java.awt.Color(255, 210, 28));
        jButCompras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButCompras.setForeground(new java.awt.Color(240, 240, 241));
        jButCompras.setText("Proveedores");
        jButCompras.setBorderPainted(false);
        jButCompras.setFocusPainted(false);
        jButCompras.setMaximumSize(new java.awt.Dimension(110, 50));
        jButCompras.setMinimumSize(new java.awt.Dimension(110, 50));
        jButCompras.setPreferredSize(new java.awt.Dimension(110, 50));
        jButCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButComprasActionPerformed(evt);
            }
        });

        jPanOpcInventario.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanOpcInventarioLayout = new javax.swing.GroupLayout(jPanOpcInventario);
        jPanOpcInventario.setLayout(jPanOpcInventarioLayout);
        jPanOpcInventarioLayout.setHorizontalGroup(
            jPanOpcInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );
        jPanOpcInventarioLayout.setVerticalGroup(
            jPanOpcInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanOpcProveedores.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanOpcProveedoresLayout = new javax.swing.GroupLayout(jPanOpcProveedores);
        jPanOpcProveedores.setLayout(jPanOpcProveedoresLayout);
        jPanOpcProveedoresLayout.setHorizontalGroup(
            jPanOpcProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanOpcProveedoresLayout.setVerticalGroup(
            jPanOpcProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        jPanOpcProductos.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanOpcProductosLayout = new javax.swing.GroupLayout(jPanOpcProductos);
        jPanOpcProductos.setLayout(jPanOpcProductosLayout);
        jPanOpcProductosLayout.setHorizontalGroup(
            jPanOpcProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanOpcProductosLayout.setVerticalGroup(
            jPanOpcProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        jButInventario.setBackground(new java.awt.Color(255, 210, 28));
        jButInventario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButInventario.setForeground(new java.awt.Color(240, 240, 241));
        jButInventario.setText("Inventario");
        jButInventario.setBorderPainted(false);
        jButInventario.setFocusPainted(false);
        jButInventario.setMaximumSize(new java.awt.Dimension(110, 50));
        jButInventario.setMinimumSize(new java.awt.Dimension(110, 50));
        jButInventario.setPreferredSize(new java.awt.Dimension(110, 50));
        jButInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButInventarioActionPerformed(evt);
            }
        });

        jButDashboard.setBackground(new java.awt.Color(255, 210, 28));
        jButDashboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButDashboard.setForeground(new java.awt.Color(240, 240, 241));
        jButDashboard.setText("Logístico");
        jButDashboard.setBorderPainted(false);
        jButDashboard.setFocusPainted(false);
        jButDashboard.setMaximumSize(new java.awt.Dimension(110, 50));
        jButDashboard.setMinimumSize(new java.awt.Dimension(110, 50));
        jButDashboard.setPreferredSize(new java.awt.Dimension(110, 50));
        jButDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDashboardActionPerformed(evt);
            }
        });

        jPanOpcServicios.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanOpcServiciosLayout = new javax.swing.GroupLayout(jPanOpcServicios);
        jPanOpcServicios.setLayout(jPanOpcServiciosLayout);
        jPanOpcServiciosLayout.setHorizontalGroup(
            jPanOpcServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        jPanOpcServiciosLayout.setVerticalGroup(
            jPanOpcServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jButCompra.setBackground(new java.awt.Color(255, 210, 28));
        jButCompra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButCompra.setForeground(new java.awt.Color(240, 240, 241));
        jButCompra.setText("Compras");
        jButCompra.setBorderPainted(false);
        jButCompra.setFocusPainted(false);
        jButCompra.setMaximumSize(new java.awt.Dimension(110, 50));
        jButCompra.setMinimumSize(new java.awt.Dimension(110, 50));
        jButCompra.setPreferredSize(new java.awt.Dimension(110, 50));
        jButCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCompraActionPerformed(evt);
            }
        });

        jPanOpcCompras.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanOpcComprasLayout = new javax.swing.GroupLayout(jPanOpcCompras);
        jPanOpcCompras.setLayout(jPanOpcComprasLayout);
        jPanOpcComprasLayout.setHorizontalGroup(
            jPanOpcComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        jPanOpcComprasLayout.setVerticalGroup(
            jPanOpcComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jtbCerrarSesion.setBackground(new java.awt.Color(255, 210, 28));
        jtbCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtbCerrarSesion.setForeground(new java.awt.Color(240, 240, 241));
        jtbCerrarSesion.setText("Cerrar Sesión ");
        jtbCerrarSesion.setBorderPainted(false);
        jtbCerrarSesion.setFocusPainted(false);
        jtbCerrarSesion.setMaximumSize(new java.awt.Dimension(110, 50));
        jtbCerrarSesion.setMinimumSize(new java.awt.Dimension(110, 50));
        jtbCerrarSesion.setPreferredSize(new java.awt.Dimension(110, 50));
        jtbCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanOpcionesDeclaracionLayout = new javax.swing.GroupLayout(jPanOpcionesDeclaracion);
        jPanOpcionesDeclaracion.setLayout(jPanOpcionesDeclaracionLayout);
        jPanOpcionesDeclaracionLayout.setHorizontalGroup(
            jPanOpcionesDeclaracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanOpcionesDeclaracionLayout.createSequentialGroup()
                .addGroup(jPanOpcionesDeclaracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanOpcionesDeclaracionLayout.createSequentialGroup()
                        .addComponent(jButCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanOpcInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanOpcProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanOpcServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanOpcionesDeclaracionLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPanOpcProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanOpcionesDeclaracionLayout.createSequentialGroup()
                        .addGroup(jPanOpcionesDeclaracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButCompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(jButInventario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanOpcCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtbCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanOpcionesDeclaracionLayout.setVerticalGroup(
            jPanOpcionesDeclaracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanOpcionesDeclaracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanOpcionesDeclaracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanOpcionesDeclaracionLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jPanOpcCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanOpcionesDeclaracionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanOpcionesDeclaracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanOpcionesDeclaracionLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanOpcInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanOpcionesDeclaracionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(jPanOpcProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jPanOpcProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanOpcServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jLabNombreContribuyente1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabNombreContribuyente1.setForeground(new java.awt.Color(240, 240, 241));
        jLabNombreContribuyente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabNombreContribuyente1.setText("Módulos");

        javax.swing.GroupLayout jPModLayout = new javax.swing.GroupLayout(jPMod);
        jPMod.setLayout(jPModLayout);
        jPModLayout.setHorizontalGroup(
            jPModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPModLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanOpcionesDeclaracion, javax.swing.GroupLayout.PREFERRED_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(jLabNombreContribuyente1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPModLayout.setVerticalGroup(
            jPModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPModLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabNombreContribuyente1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanOpcionesDeclaracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPMod, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelVerTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPMod, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelVerTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButComprasActionPerformed

    }//GEN-LAST:event_jButComprasActionPerformed

    private void jButInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButInventarioActionPerformed

    }//GEN-LAST:event_jButInventarioActionPerformed

    private void jtbCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbCerrarSesionActionPerformed
        this.setVisible(false);
        Main_Trappi log = new Main_Trappi();
        log.setVisible(true);
    }//GEN-LAST:event_jtbCerrarSesionActionPerformed

    private void jButDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDashboardActionPerformed

    }//GEN-LAST:event_jButDashboardActionPerformed

    private void jButCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCompraActionPerformed

    }//GEN-LAST:event_jButCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Trappi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Trappi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Trappi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Trappi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Trappi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelVerTodos;
    private javax.swing.JButton jButCompra;
    private javax.swing.JButton jButCompras;
    private javax.swing.JButton jButDashboard;
    private javax.swing.JButton jButInventario;
    private javax.swing.JLabel jIVA;
    private javax.swing.JLabel jLSidimLogo;
    private javax.swing.JLabel jLabNombreContribuyente1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPEncabezado;
    private javax.swing.JPanel jPMod;
    private javax.swing.JPanel jPanOpcCompras;
    private javax.swing.JPanel jPanOpcInventario;
    private javax.swing.JPanel jPanOpcProductos;
    private javax.swing.JPanel jPanOpcProveedores;
    private javax.swing.JPanel jPanOpcServicios;
    private javax.swing.JPanel jPanOpcionesDeclaracion;
    private javax.swing.JLabel jValor;
    private javax.swing.JButton jtbCerrarSesion;
    // End of variables declaration//GEN-END:variables
}
