/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.epn.trappi.gui.proveedores;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Peterca
 */
public class Principal extends javax.swing.JFrame {
    
    private ArrayList<JPanel> panelesOpciones = new ArrayList<>();

    /**
     * Creates new form Principal1
     */
    public Principal() {
        initComponents();
        new CambiaPanel(PanelVerTodos, new guiAnalizador(PanelVerTodos));
        ponerTituloYsub("Dashboard", "Genere una solicitud de compra de productos con bajo stock");
        panelesOpciones.add(jPanOpcProductos);
        panelesOpciones.add(jPanOpcServicios);
        panelesOpciones.add(jPanOpcInventario);
        panelesOpciones.add(jPanOpcProveedores);
        panelesOpciones.add(jPanOpcCompras);
        jBCerrarSesion.setVisible(false);
        showPanel(null);
    }
    
    private void showPanel(JPanel panel) {
        panelesOpciones.forEach(p
                -> {
            if (p.equals(panel)) {
                if (!p.isVisible()) {
                    p.setVisible(true);
                } else {
                    p.setVisible(false);
                }
            } else {
                p.setVisible(false);
            }
        });
    }
    
    private void ponerTituloYsub(String titulo, String subtitulo) {
        labelTitulo.setText(titulo);
        labelSubTitulo.setText(subtitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPEncabezado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLSidimLogo = new javax.swing.JLabel();
        jPMod = new javax.swing.JPanel();
        jPanOpcionesDeclaracion = new javax.swing.JPanel();
        jButCompras = new javax.swing.JButton();
        jButProductos = new javax.swing.JButton();
        jPanOpcInventario = new javax.swing.JPanel();
        jButVerTodFactura = new javax.swing.JButton();
        jPanOpcProveedores = new javax.swing.JPanel();
        jButRegNotasVenta = new javax.swing.JButton();
        jButVerTodNotasVenta = new javax.swing.JButton();
        jPanOpcProductos = new javax.swing.JPanel();
        jButRegistrarProducto = new javax.swing.JButton();
        jButListarProductos = new javax.swing.JButton();
        jButInventario = new javax.swing.JButton();
        jButServicios = new javax.swing.JButton();
        jButDashboard = new javax.swing.JButton();
        jButRealizarCompras = new javax.swing.JButton();
        jPanOpcServicios = new javax.swing.JPanel();
        jButListarServicios = new javax.swing.JButton();
        jButRegistrarServicios = new javax.swing.JButton();
        jButCompra = new javax.swing.JButton();
        jPanOpcCompras = new javax.swing.JPanel();
        jButVerTodFactura5 = new javax.swing.JButton();
        jLabNombreContribuyente1 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelSubTitulo = new javax.swing.JLabel();
        jPaCerrarSesion = new javax.swing.JPanel();
        jBCerrarSesion = new javax.swing.JButton();
        PanelVerTodos = new javax.swing.JPanel();
        jIVA = new javax.swing.JLabel();
        jValor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPEncabezado.setBackground(new java.awt.Color(54, 112, 171));

        jLabel2.setBackground(new java.awt.Color(80, 125, 180));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 241));
        jLabel2.setText("Bienvenido: Administrador 1");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPEncabezadoLayout = new javax.swing.GroupLayout(jPEncabezado);
        jPEncabezado.setLayout(jPEncabezadoLayout);
        jPEncabezadoLayout.setHorizontalGroup(
            jPEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEncabezadoLayout.createSequentialGroup()
                .addComponent(jLSidimLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(23, 23, 23))
        );
        jPEncabezadoLayout.setVerticalGroup(
            jPEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLSidimLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPMod.setBackground(new java.awt.Color(51, 51, 51));
        jPMod.setForeground(new java.awt.Color(51, 51, 51));
        jPMod.setMaximumSize(new java.awt.Dimension(300, 200));
        jPMod.setPreferredSize(new java.awt.Dimension(300, 280));

        jPanOpcionesDeclaracion.setBackground(new java.awt.Color(51, 51, 51));

        jButCompras.setBackground(new java.awt.Color(38, 35, 36));
        jButCompras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButCompras.setForeground(new java.awt.Color(240, 240, 241));
        jButCompras.setText("Proveedores");
        jButCompras.setBorderPainted(false);
        jButCompras.setFocusPainted(false);
        jButCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButComprasActionPerformed(evt);
            }
        });

        jButProductos.setBackground(new java.awt.Color(38, 35, 36));
        jButProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButProductos.setForeground(new java.awt.Color(240, 240, 241));
        jButProductos.setText("Productos");
        jButProductos.setBorderPainted(false);
        jButProductos.setFocusPainted(false);
        jButProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButProductosActionPerformed(evt);
            }
        });

        jPanOpcInventario.setBackground(new java.awt.Color(51, 51, 51));

        jButVerTodFactura.setBackground(new java.awt.Color(85, 85, 85));
        jButVerTodFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButVerTodFactura.setForeground(new java.awt.Color(240, 240, 241));
        jButVerTodFactura.setText("Ver Inventario");
        jButVerTodFactura.setBorderPainted(false);
        jButVerTodFactura.setFocusPainted(false);
        jButVerTodFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVerTodFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanOpcInventarioLayout = new javax.swing.GroupLayout(jPanOpcInventario);
        jPanOpcInventario.setLayout(jPanOpcInventarioLayout);
        jPanOpcInventarioLayout.setHorizontalGroup(
            jPanOpcInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButVerTodFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanOpcInventarioLayout.setVerticalGroup(
            jPanOpcInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButVerTodFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanOpcProveedores.setBackground(new java.awt.Color(51, 51, 51));

        jButRegNotasVenta.setBackground(new java.awt.Color(85, 85, 85));
        jButRegNotasVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButRegNotasVenta.setForeground(new java.awt.Color(240, 240, 241));
        jButRegNotasVenta.setText("Registrar Proveedor");
        jButRegNotasVenta.setBorderPainted(false);
        jButRegNotasVenta.setFocusPainted(false);
        jButRegNotasVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegNotasVentaActionPerformed(evt);
            }
        });

        jButVerTodNotasVenta.setBackground(new java.awt.Color(85, 85, 85));
        jButVerTodNotasVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButVerTodNotasVenta.setForeground(new java.awt.Color(240, 240, 241));
        jButVerTodNotasVenta.setText("Lista Proveedores");
        jButVerTodNotasVenta.setBorderPainted(false);
        jButVerTodNotasVenta.setFocusPainted(false);
        jButVerTodNotasVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVerTodNotasVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanOpcProveedoresLayout = new javax.swing.GroupLayout(jPanOpcProveedores);
        jPanOpcProveedores.setLayout(jPanOpcProveedoresLayout);
        jPanOpcProveedoresLayout.setHorizontalGroup(
            jPanOpcProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanOpcProveedoresLayout.createSequentialGroup()
                .addGroup(jPanOpcProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButVerTodNotasVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButRegNotasVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanOpcProveedoresLayout.setVerticalGroup(
            jPanOpcProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanOpcProveedoresLayout.createSequentialGroup()
                .addComponent(jButRegNotasVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButVerTodNotasVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanOpcProductos.setBackground(new java.awt.Color(51, 51, 51));

        jButRegistrarProducto.setBackground(new java.awt.Color(85, 85, 85));
        jButRegistrarProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButRegistrarProducto.setForeground(new java.awt.Color(240, 240, 241));
        jButRegistrarProducto.setText("Registrar Producto");
        jButRegistrarProducto.setBorderPainted(false);
        jButRegistrarProducto.setFocusPainted(false);
        jButRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegistrarProductoActionPerformed(evt);
            }
        });

        jButListarProductos.setBackground(new java.awt.Color(85, 85, 85));
        jButListarProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButListarProductos.setForeground(new java.awt.Color(240, 240, 241));
        jButListarProductos.setText("Lista Productos");
        jButListarProductos.setBorderPainted(false);
        jButListarProductos.setFocusPainted(false);
        jButListarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButListarProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanOpcProductosLayout = new javax.swing.GroupLayout(jPanOpcProductos);
        jPanOpcProductos.setLayout(jPanOpcProductosLayout);
        jPanOpcProductosLayout.setHorizontalGroup(
            jPanOpcProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanOpcProductosLayout.createSequentialGroup()
                .addGroup(jPanOpcProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButListarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanOpcProductosLayout.setVerticalGroup(
            jPanOpcProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanOpcProductosLayout.createSequentialGroup()
                .addComponent(jButRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButListarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButInventario.setBackground(new java.awt.Color(38, 35, 36));
        jButInventario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButInventario.setForeground(new java.awt.Color(240, 240, 241));
        jButInventario.setText("Inventario");
        jButInventario.setBorderPainted(false);
        jButInventario.setFocusPainted(false);
        jButInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButInventarioActionPerformed(evt);
            }
        });

        jButServicios.setBackground(new java.awt.Color(38, 35, 36));
        jButServicios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButServicios.setForeground(new java.awt.Color(240, 240, 241));
        jButServicios.setText("Servicios");
        jButServicios.setBorderPainted(false);
        jButServicios.setFocusPainted(false);
        jButServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButServiciosActionPerformed(evt);
            }
        });

        jButDashboard.setBackground(new java.awt.Color(38, 35, 36));
        jButDashboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButDashboard.setForeground(new java.awt.Color(240, 240, 241));
        jButDashboard.setText("Dashboard");
        jButDashboard.setBorderPainted(false);
        jButDashboard.setFocusPainted(false);
        jButDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDashboardActionPerformed(evt);
            }
        });

        jButRealizarCompras.setBackground(new java.awt.Color(38, 35, 36));
        jButRealizarCompras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButRealizarCompras.setForeground(new java.awt.Color(240, 240, 241));
        jButRealizarCompras.setText("Realizar Compras");
        jButRealizarCompras.setBorderPainted(false);
        jButRealizarCompras.setFocusPainted(false);
        jButRealizarCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRealizarComprasActionPerformed(evt);
            }
        });

        jPanOpcServicios.setBackground(new java.awt.Color(51, 51, 51));

        jButListarServicios.setBackground(new java.awt.Color(85, 85, 85));
        jButListarServicios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButListarServicios.setForeground(new java.awt.Color(240, 240, 241));
        jButListarServicios.setText("Lista Servicios");
        jButListarServicios.setBorderPainted(false);
        jButListarServicios.setFocusPainted(false);
        jButListarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButListarServiciosActionPerformed(evt);
            }
        });

        jButRegistrarServicios.setBackground(new java.awt.Color(85, 85, 85));
        jButRegistrarServicios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButRegistrarServicios.setForeground(new java.awt.Color(240, 240, 241));
        jButRegistrarServicios.setText("Registrar Servicio");
        jButRegistrarServicios.setBorderPainted(false);
        jButRegistrarServicios.setFocusPainted(false);
        jButRegistrarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegistrarServiciosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanOpcServiciosLayout = new javax.swing.GroupLayout(jPanOpcServicios);
        jPanOpcServicios.setLayout(jPanOpcServiciosLayout);
        jPanOpcServiciosLayout.setHorizontalGroup(
            jPanOpcServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButListarServicios, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(jButRegistrarServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanOpcServiciosLayout.setVerticalGroup(
            jPanOpcServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanOpcServiciosLayout.createSequentialGroup()
                .addComponent(jButRegistrarServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButListarServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButCompra.setBackground(new java.awt.Color(38, 35, 36));
        jButCompra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButCompra.setForeground(new java.awt.Color(240, 240, 241));
        jButCompra.setText("Compras");
        jButCompra.setBorderPainted(false);
        jButCompra.setFocusPainted(false);
        jButCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCompraActionPerformed(evt);
            }
        });

        jPanOpcCompras.setBackground(new java.awt.Color(51, 51, 51));

        jButVerTodFactura5.setBackground(new java.awt.Color(85, 85, 85));
        jButVerTodFactura5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButVerTodFactura5.setForeground(new java.awt.Color(240, 240, 241));
        jButVerTodFactura5.setText("Lista Compras");
        jButVerTodFactura5.setBorderPainted(false);
        jButVerTodFactura5.setFocusPainted(false);
        jButVerTodFactura5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVerTodFactura5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanOpcComprasLayout = new javax.swing.GroupLayout(jPanOpcCompras);
        jPanOpcCompras.setLayout(jPanOpcComprasLayout);
        jPanOpcComprasLayout.setHorizontalGroup(
            jPanOpcComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButVerTodFactura5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanOpcComprasLayout.setVerticalGroup(
            jPanOpcComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanOpcComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButVerTodFactura5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanOpcionesDeclaracionLayout = new javax.swing.GroupLayout(jPanOpcionesDeclaracion);
        jPanOpcionesDeclaracion.setLayout(jPanOpcionesDeclaracionLayout);
        jPanOpcionesDeclaracionLayout.setHorizontalGroup(
            jPanOpcionesDeclaracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanOpcionesDeclaracionLayout.createSequentialGroup()
                .addGroup(jPanOpcionesDeclaracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanOpcInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanOpcionesDeclaracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanOpcProductos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButRealizarCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanOpcServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanOpcionesDeclaracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanOpcProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanOpcionesDeclaracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanOpcCompras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButCompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanOpcionesDeclaracionLayout.setVerticalGroup(
            jPanOpcionesDeclaracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanOpcionesDeclaracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButRealizarCompras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanOpcCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanOpcInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButCompras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanOpcProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanOpcProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButServicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanOpcServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jLabNombreContribuyente1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabNombreContribuyente1.setForeground(new java.awt.Color(240, 240, 241));
        jLabNombreContribuyente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabNombreContribuyente1.setText("PROVEEDORES");

        javax.swing.GroupLayout jPModLayout = new javax.swing.GroupLayout(jPMod);
        jPMod.setLayout(jPModLayout);
        jPModLayout.setHorizontalGroup(
            jPModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPModLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanOpcionesDeclaracion, javax.swing.GroupLayout.PREFERRED_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(jLabNombreContribuyente1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPModLayout.setVerticalGroup(
            jPModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPModLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabNombreContribuyente1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanOpcionesDeclaracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(38, 35, 36));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Editar Nota de Crédito");

        labelSubTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelSubTitulo.setForeground(new java.awt.Color(163, 164, 166));
        labelSubTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubTitulo.setText("Llena el formulario para editar la Nota de Crédito en Compras.");

        jPaCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));

        jBCerrarSesion.setBackground(new java.awt.Color(0, 153, 51));
        jBCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBCerrarSesion.setForeground(new java.awt.Color(240, 240, 241));
        jBCerrarSesion.setText("Cerrar Sesión");
        jBCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaCerrarSesionLayout = new javax.swing.GroupLayout(jPaCerrarSesion);
        jPaCerrarSesion.setLayout(jPaCerrarSesionLayout);
        jPaCerrarSesionLayout.setHorizontalGroup(
            jPaCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPaCerrarSesionLayout.setVerticalGroup(
            jPaCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaCerrarSesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelVerTodos.setBackground(new java.awt.Color(255, 255, 255));
        PanelVerTodos.setLayout(new javax.swing.BoxLayout(PanelVerTodos, javax.swing.BoxLayout.LINE_AXIS));

        jIVA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PanelVerTodos.add(jIVA);

        jValor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PanelVerTodos.add(jValor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPMod, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo)
                            .addComponent(labelSubTitulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPaCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelVerTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jPEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPMod, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(labelSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPaCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(PanelVerTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        if (jPaCerrarSesion.isVisible()) {
            jPaCerrarSesion.setVisible(false);
        } else {
            jPaCerrarSesion.setVisible(true);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDashboardActionPerformed
        new CambiaPanel(PanelVerTodos, new guiAnalizador(PanelVerTodos));
        showPanel(null);
    }//GEN-LAST:event_jButDashboardActionPerformed

    private void jButComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButComprasActionPerformed
        if (jPanOpcInventario.isVisible()) {
            jPanOpcInventario.setVisible(false);
        }
        if (jPanOpcProductos.isVisible()) {
            jPanOpcProductos.setVisible(false);
        }
        if (jPanOpcProveedores.isVisible()) {
            jPanOpcProveedores.setVisible(false);
        } else {
            jPanOpcProveedores.setVisible(true);
        }
    }//GEN-LAST:event_jButComprasActionPerformed

    private void jButVerTodFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVerTodFacturaActionPerformed
        new CambiaPanel(PanelVerTodos, new guiInventarioPanel());
        ponerTituloYsub("Inventario", "Lista de los productos del inventario.");
    }//GEN-LAST:event_jButVerTodFacturaActionPerformed

    private void jButRegNotasVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegNotasVentaActionPerformed
        new CambiaPanel(PanelVerTodos, new guiProveedores());
        ponerTituloYsub("Proveedores", "Llena el formulario para registrar Proveedores.");
    }//GEN-LAST:event_jButRegNotasVentaActionPerformed

    private void jButVerTodNotasVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVerTodNotasVentaActionPerformed
        new CambiaPanel(PanelVerTodos, new guiListaProveedores());
        ponerTituloYsub("Actualizar Proveedores", "Consulta de Proveedores para su Actualización.");
    }//GEN-LAST:event_jButVerTodNotasVentaActionPerformed

    private void jButRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegistrarProductoActionPerformed
        new CambiaPanel(PanelVerTodos, new guiRegistrarProductoPanel());
        ponerTituloYsub("Nuevo Producto", "Llena el formulario para registrar un nuevo producto");
    }//GEN-LAST:event_jButRegistrarProductoActionPerformed

    private void jButListarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButListarProductosActionPerformed
        new CambiaPanel(PanelVerTodos, new guiListaProductosPanel());
        ponerTituloYsub("Productos", "Lista de los productos registrados");
    }//GEN-LAST:event_jButListarProductosActionPerformed

    private void jBCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarSesionActionPerformed

    }//GEN-LAST:event_jBCerrarSesionActionPerformed

    private void jButInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButInventarioActionPerformed
        showPanel(jPanOpcInventario);
    }//GEN-LAST:event_jButInventarioActionPerformed

    private void jButListarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButListarServiciosActionPerformed
        new CambiaPanel(PanelVerTodos, new guiListaServiciosPanel());
        ponerTituloYsub("Servicios", "Llena el formulario para registrar un nuevo servicio");
    }//GEN-LAST:event_jButListarServiciosActionPerformed

    private void jButRegistrarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegistrarServiciosActionPerformed
        new CambiaPanel(PanelVerTodos, new guiRegistrarServicioPanel());
        ponerTituloYsub("Servicios", "Lista de los servicios adquiridos");
    }//GEN-LAST:event_jButRegistrarServiciosActionPerformed

    private void jButServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButServiciosActionPerformed
        showPanel(jPanOpcServicios);
    }//GEN-LAST:event_jButServiciosActionPerformed

    private void jButProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButProductosActionPerformed
        showPanel(jPanOpcProductos);
    }//GEN-LAST:event_jButProductosActionPerformed

    private void jButRealizarComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRealizarComprasActionPerformed
        new CambiaPanel(PanelVerTodos, new guiFormularioComprasPanel(PanelVerTodos));
    }//GEN-LAST:event_jButRealizarComprasActionPerformed

    private void jButCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCompraActionPerformed
        showPanel(jPanOpcCompras);
    }//GEN-LAST:event_jButCompraActionPerformed

    private void jButVerTodFactura5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVerTodFactura5ActionPerformed
        try {
            new CambiaPanel(PanelVerTodos, new guiComprasPanel());
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        showPanel(null);
    }//GEN-LAST:event_jButVerTodFactura5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelVerTodos;
    private javax.swing.JButton jBCerrarSesion;
    private javax.swing.JButton jButCompra;
    private javax.swing.JButton jButCompras;
    private javax.swing.JButton jButDashboard;
    private javax.swing.JButton jButInventario;
    private javax.swing.JButton jButListarProductos;
    private javax.swing.JButton jButListarServicios;
    private javax.swing.JButton jButProductos;
    private javax.swing.JButton jButRealizarCompras;
    private javax.swing.JButton jButRegNotasVenta;
    private javax.swing.JButton jButRegistrarProducto;
    private javax.swing.JButton jButRegistrarServicios;
    private javax.swing.JButton jButServicios;
    private javax.swing.JButton jButVerTodFactura;
    private javax.swing.JButton jButVerTodFactura5;
    private javax.swing.JButton jButVerTodNotasVenta;
    private javax.swing.JLabel jIVA;
    private javax.swing.JLabel jLSidimLogo;
    private javax.swing.JLabel jLabNombreContribuyente1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPEncabezado;
    private javax.swing.JPanel jPMod;
    private javax.swing.JPanel jPaCerrarSesion;
    private javax.swing.JPanel jPanOpcCompras;
    private javax.swing.JPanel jPanOpcInventario;
    private javax.swing.JPanel jPanOpcProductos;
    private javax.swing.JPanel jPanOpcProveedores;
    private javax.swing.JPanel jPanOpcServicios;
    private javax.swing.JPanel jPanOpcionesDeclaracion;
    private javax.swing.JLabel jValor;
    private javax.swing.JLabel labelSubTitulo;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
