create table BIEN
(
    IDENTIFICADORBIEN2 int identity
        constraint PK_BIEN
            primary key nonclustered,
    RUC                char(13)     not null
        constraint FK_BIEN_TIENE_PROVEEDO
            references PROVEEDOR,
    NOMBREBIEN         varchar(100) not null,
    PRECIOBIEN         float        not null,
    TIPOBIEN           varchar(100),
    MARCA              varchar(30),
    CATEGORIA          varchar(30)
)
go

INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (4, N'7043728305001', N'Jugo', 3.1, N'Producto', N'Fanta', N'Normal');
INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (5, N'1023598647001', N'Leche', 0.8, N'Producto', N'Nestle', N'Normal');
INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (8, N'7043728305420', N'Mantenimiento de rutina', 15, N'Servicio', N'Vulcanizadora Oro', N'Normal');
INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (9, N'7043728305420', N'Revisión por mecanico', 45, N'Servicio', N'Vulcanizadora Oro', N'Normal');
INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (12, N'1023598647001', N'Shampoo', 2.6, N'Producto', N'Sedal ', N'Normal');
INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (13, N'1023598647001', N'Pasta dental Colgate', 1.6, N'Producto', N'Colgate', N'Normal');
INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (14, N'7043728305420', N'Reparación por mecánico', 250, N'Servicio', N'Vulcanizadora Oro', N'Normal');
INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (15, N'1023598647001', N'Fideos', 3.75, N'Producto', N'Don Vitorio', N'Normal');
INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (18, N'1722793881001', N'MacBook Pro', 1679, N'Producto', N'Apple', N'VIP');
INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (19, N'1723471767001', N'Enderezada y Pintura', 45, N'Servicio', N'SegMotors Ingeniería', N'Normal');
INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (20, N'1722793881001', N'Horsebit Shoulder Bag', 2690, N'Producto', N'Gucci', N'VIP');
INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (21, N'1722793881001', N'Supreme Box Logo Sticker', 420, N'Producto', N'Supreme', N'VIP');
INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (6, N'7043728305001', N'Papel higienico', 2.8, N'Producto', N'Familia', N'Normal');
INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (7, N'7043728305001', N'Aceite', 2.99, N'Producto', N'Favorita', N'Normal');
INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (10, N'7043728305001', N'Chocolate', 0.5, N'Producto', N'Pacari', N'Normal');
INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (11, N'7043728305420', N'Cambio de Batería', 100, N'Servicio', N'Vulcanizadora Oro', N'Normal');
INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (16, N'1722793881001', N'Dom Pérignon', 270, N'Producto', N'Moet Chandon', N'VIP');
INSERT INTO trappiDb.dbo.BIEN (IDENTIFICADORBIEN2, RUC, NOMBREBIEN, PRECIOBIEN, TIPOBIEN, MARCA, CATEGORIA) VALUES (17, N'1722793881001', N'Mochila Ophidia GG', 1754, N'Producto', N'Gucci', N'VIP');