create table SOLICITUDPAGOMANTENIMIENTO
(
    NUMSOLICITUD           int      not null
        constraint PK_SOLICITUDPAGOMANTENIMIENTO
            primary key nonclustered,
    IDENTIFICADORBIEN2     int      not null
        constraint FK_SOLICITU_RELATIONS_BIEN
            references BIEN,
    IDMANTENIMIENTO        int
        constraint FK_SOLICITU_MANTENIMI_MANTENIM
            references MANTENIMIENTO,
    FECHASOLICITUD         datetime not null,
    ESTADOSOLMANTENIMIENTO varchar(1024)
)
go

INSERT INTO trappiDb.dbo.SOLICITUDPAGOMANTENIMIENTO (NUMSOLICITUD, IDENTIFICADORBIEN2, IDMANTENIMIENTO, FECHASOLICITUD, ESTADOSOLMANTENIMIENTO) VALUES (1, 8, 1, N'2021-02-06 17:52:28.000', N'Realizado');
INSERT INTO trappiDb.dbo.SOLICITUDPAGOMANTENIMIENTO (NUMSOLICITUD, IDENTIFICADORBIEN2, IDMANTENIMIENTO, FECHASOLICITUD, ESTADOSOLMANTENIMIENTO) VALUES (2, 8, 1, N'2021-02-06 18:47:41.000', N'Realizado');
INSERT INTO trappiDb.dbo.SOLICITUDPAGOMANTENIMIENTO (NUMSOLICITUD, IDENTIFICADORBIEN2, IDMANTENIMIENTO, FECHASOLICITUD, ESTADOSOLMANTENIMIENTO) VALUES (5, 8, 178, N'2021-02-14 23:42:19.000', N'true');
INSERT INTO trappiDb.dbo.SOLICITUDPAGOMANTENIMIENTO (NUMSOLICITUD, IDENTIFICADORBIEN2, IDMANTENIMIENTO, FECHASOLICITUD, ESTADOSOLMANTENIMIENTO) VALUES (21, 8, 503, N'2021-02-14 23:42:22.000', N'Aprobado');
INSERT INTO trappiDb.dbo.SOLICITUDPAGOMANTENIMIENTO (NUMSOLICITUD, IDENTIFICADORBIEN2, IDMANTENIMIENTO, FECHASOLICITUD, ESTADOSOLMANTENIMIENTO) VALUES (45, 8, 246, N'2021-02-14 23:51:17.000', N'true');
INSERT INTO trappiDb.dbo.SOLICITUDPAGOMANTENIMIENTO (NUMSOLICITUD, IDENTIFICADORBIEN2, IDMANTENIMIENTO, FECHASOLICITUD, ESTADOSOLMANTENIMIENTO) VALUES (12, 8, 234, N'2021-02-14 23:54:17.000', N'Aceptado');
INSERT INTO trappiDb.dbo.SOLICITUDPAGOMANTENIMIENTO (NUMSOLICITUD, IDENTIFICADORBIEN2, IDMANTENIMIENTO, FECHASOLICITUD, ESTADOSOLMANTENIMIENTO) VALUES (8, 14, 245, N'2021-02-15 01:45:11.000', N'Aprobado');
INSERT INTO trappiDb.dbo.SOLICITUDPAGOMANTENIMIENTO (NUMSOLICITUD, IDENTIFICADORBIEN2, IDMANTENIMIENTO, FECHASOLICITUD, ESTADOSOLMANTENIMIENTO) VALUES (100, 9, 6, N'2021-02-14 19:22:59.000', N'En espera');
INSERT INTO trappiDb.dbo.SOLICITUDPAGOMANTENIMIENTO (NUMSOLICITUD, IDENTIFICADORBIEN2, IDMANTENIMIENTO, FECHASOLICITUD, ESTADOSOLMANTENIMIENTO) VALUES (101, 14, 6, N'2021-02-14 19:23:13.000', N'En espera');
INSERT INTO trappiDb.dbo.SOLICITUDPAGOMANTENIMIENTO (NUMSOLICITUD, IDENTIFICADORBIEN2, IDMANTENIMIENTO, FECHASOLICITUD, ESTADOSOLMANTENIMIENTO) VALUES (102, 8, 6, N'2021-02-14 19:23:41.000', N'En espera');
INSERT INTO trappiDb.dbo.SOLICITUDPAGOMANTENIMIENTO (NUMSOLICITUD, IDENTIFICADORBIEN2, IDMANTENIMIENTO, FECHASOLICITUD, ESTADOSOLMANTENIMIENTO) VALUES (15, 9, 345, N'2021-02-15 12:09:56.000', N'Aprobado');
INSERT INTO trappiDb.dbo.SOLICITUDPAGOMANTENIMIENTO (NUMSOLICITUD, IDENTIFICADORBIEN2, IDMANTENIMIENTO, FECHASOLICITUD, ESTADOSOLMANTENIMIENTO) VALUES (20, 8, 503, N'2021-02-14 23:37:04.000', N'En espera');