create table COMPRABIEN
(
    IDENTIFICADORBIEN2  int not null
        constraint FK_COMPRABI_COMPRABIE_BIEN
            references BIEN,
    IDENTIFICADORCOMPRA int not null
        constraint FK_COMPRABI_COMPRABIE_COMPRA
            references COMPRA,
    CANTIDADBIEN        int,
    constraint PK_COMPRABIEN
        primary key nonclustered (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA)
)
go

INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (5, 1, 3);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (6, 1, 2);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (4, 1, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (5, 6, 3);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (7, 7, 100);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (4, 8, 100);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (6, 9, 100);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (6, 12, 15);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (4, 12, 25);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (4, 13, 25);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (5, 18, 50);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (5, 21, 100);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (5, 22, 5);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (6, 23, 4);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (7, 23, 3);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (5, 24, 900);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (5, 25, 100);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (6, 26, 100);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (4, 26, 100);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (7, 26, 100);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (6, 27, 50);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (4, 27, 50);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (4, 28, 10);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (4, 29, 10);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (6, 30, 100);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (4, 31, 250);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (6, 32, 400);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (5, 33, 150);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (5, 34, 150);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (4, 35, 20);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (7, 36, 100);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (6, 37, 69);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (6, 38, 4);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (12, 46, 100);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (13, 46, 100);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (15, 46, 100);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (10, 48, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (15, 49, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (16, 50, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (10, 51, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (18, 57, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (17, 58, 9);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (4, 59, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (21, 60, 2);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (15, 61, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (8, 64, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (8, 65, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (8, 66, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (8, 67, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (8, 68, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (8, 70, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (18, 73, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (5, 10, 100);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (6, 10, 100);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (6, 11, 100);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (4, 14, 7);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (7, 14, 9);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (7, 15, 9);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (8, 17, 6);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (5, 19, 50);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (5, 20, 100);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (18, 39, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (12, 40, 5);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (13, 40, 5);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (15, 40, 10);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (15, 42, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (15, 43, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (10, 44, 11);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (16, 45, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (16, 47, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (21, 52, 2);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (20, 53, 2);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (8, 55, 0);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (8, 56, 0);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (8, 62, 0);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (8, 63, 0);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (8, 69, 0);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (8, 71, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (14, 72, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (9, 74, 1);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (6, 16, 69);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (7, 16, 69);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (15, 41, 4);
INSERT INTO trappiDb.dbo.COMPRABIEN (IDENTIFICADORBIEN2, IDENTIFICADORCOMPRA, CANTIDADBIEN) VALUES (8, 54, 0);