create table COMPRA
(
    IDENTIFICADORCOMPRA int identity
        constraint PK_COMPRA
            primary key nonclustered,
    ESTADOCOMPRA        varchar(30) not null,
    MONTOTOTAL          float,
    FECHACOMPRA         varchar(30)
)
go

INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (1, N'Entregado', 19.75, N'28/02/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (2, N'entregado', 19.75, N'28/02/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (3, N'entregado', 19.75, N'28/02/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (4, N'entregado', 19.75, N'28/02/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (7, N'Entregado', 299, N'01/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (9, N'Entregado', 193.2, N'02/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (12, N'Entregado', 167, N'02/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (13, N'Entregado', 125, N'02/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (18, N'Entregado', 40, N'06/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (21, N'Entregado', 80, N'07/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (22, N'Entregado', 4, N'07/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (23, N'Entregado', 20.17, N'07/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (24, N'Entregado', 720, N'08/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (25, N'Entregado', 80, N'08/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (26, N'Entregado', 889, N'08/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (27, N'Entregado', 295, N'08/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (28, N'Entregado', 31, N'08/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (29, N'Entregado', 31, N'08/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (30, N'Entregado', 280, N'08/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (31, N'Entregado', 775, N'08/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (32, N'Entregado', 1120, N'08/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (33, N'Entregado', 120, N'08/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (34, N'Entregado', 120, N'08/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (35, N'Entregado', 62, N'08/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (36, N'Entregado', 299, N'08/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (37, N'Entregado', 193.2, N'13/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (38, N'Entregado', 11.2, N'13/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (46, N'Entregado', 795, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (48, N'Entregado', 0.5, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (49, N'Entregado', 3.75, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (50, N'Entregado', 270, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (51, N'Entregado', 0.5, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (57, N'Entregado', 1679, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (58, N'Entregado', 15786, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (59, N'Entregado', 3.1, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (60, N'Entregado', 840, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (61, N'Entregado', 3.75, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (64, N'Entregado', 15, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (65, N'Entregado', 15, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (66, N'Entregado', 15, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (67, N'Entregado', 15, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (68, N'Entregado', 15, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (70, N'Entregado', 15, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (73, N'Entregado', 1679, N'15/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (8, N'Entregado', 2100, N'02/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (6, N'Entregado', 27.8, N'01/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (44, N'Entregado', 5.5, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (45, N'Entregado', 270, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (47, N'Entregado', 270, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (52, N'Entregado', 840, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (53, N'Entregado', 5380, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (55, N'Entregado', 0, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (56, N'Entregado', 0, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (63, N'Entregado', 0, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (74, N'Pendiente', 45, N'15/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (10, N'Entregado', 1776.3, N'02/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (11, N'Entregado', 1176, N'02/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (14, N'Entregado', 61.910000000000004, N'02/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (15, N'Entregado', 26.910000000000004, N'02/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (17, N'Entregado', 90, N'05/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (19, N'Entregado', 40, N'07/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (20, N'Entregado', 80, N'07/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (39, N'Entregado', 1679, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (40, N'Entregado', 96, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (42, N'Entregado', 3.75, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (43, N'Entregado', 3.75, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (62, N'Entregado', 0, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (69, N'Entregado', 0, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (71, N'Entregado', 15, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (72, N'Entregado', 250, N'15/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (16, N'Entregado', 399.51, N'02/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (41, N'Entregado', 15, N'14/03/2021');
INSERT INTO trappiDb.dbo.COMPRA (IDENTIFICADORCOMPRA, ESTADOCOMPRA, MONTOTOTAL, FECHACOMPRA) VALUES (54, N'Entregado', 0, N'14/03/2021');