create table PRUEBAADMISION
(
    IDPRUEBA         int not null
        constraint PK_PRUEBAADMISION
            primary key nonclustered,
    ID_ASP           int
        constraint FK_PRUEBAAD_RELATIONS_ASPIRANT
            references ASPIRANTE,
    PUNTAJEPRUEBA    int,
    ACTITUDESPRUEBA  varchar(1024),
    APTITUDESPRUEBA  varchar(1024),
    APROBACIONPRUEBA varchar(1024)
)
go

INSERT INTO trappiDb.dbo.PRUEBAADMISION (IDPRUEBA, ID_ASP, PUNTAJEPRUEBA, ACTITUDESPRUEBA, APTITUDESPRUEBA, APROBACIONPRUEBA) VALUES (1, 1, 19, N'feliz', N'innovador', N'Pendiente');
INSERT INTO trappiDb.dbo.PRUEBAADMISION (IDPRUEBA, ID_ASP, PUNTAJEPRUEBA, ACTITUDESPRUEBA, APTITUDESPRUEBA, APROBACIONPRUEBA) VALUES (2, 2, 19, N'feliz contento', N'creativo', N'Pendiente');
INSERT INTO trappiDb.dbo.PRUEBAADMISION (IDPRUEBA, ID_ASP, PUNTAJEPRUEBA, ACTITUDESPRUEBA, APTITUDESPRUEBA, APROBACIONPRUEBA) VALUES (3, 3, 15, N'triste', N'emprendedor', N'Pendiente');
INSERT INTO trappiDb.dbo.PRUEBAADMISION (IDPRUEBA, ID_ASP, PUNTAJEPRUEBA, ACTITUDESPRUEBA, APTITUDESPRUEBA, APROBACIONPRUEBA) VALUES (4, 4, 15, N'triste', N'emprendedor', N'Pendiente');
INSERT INTO trappiDb.dbo.PRUEBAADMISION (IDPRUEBA, ID_ASP, PUNTAJEPRUEBA, ACTITUDESPRUEBA, APTITUDESPRUEBA, APROBACIONPRUEBA) VALUES (5, 5, 18, N'triste', N'emprendedor', N'Pendiente');
INSERT INTO trappiDb.dbo.PRUEBAADMISION (IDPRUEBA, ID_ASP, PUNTAJEPRUEBA, ACTITUDESPRUEBA, APTITUDESPRUEBA, APROBACIONPRUEBA) VALUES (6, 6, 17, N'alegre', N'emprendedor', N'Pendiente');
INSERT INTO trappiDb.dbo.PRUEBAADMISION (IDPRUEBA, ID_ASP, PUNTAJEPRUEBA, ACTITUDESPRUEBA, APTITUDESPRUEBA, APROBACIONPRUEBA) VALUES (7, 7, 17, N'agil inteligente alegre optimista', N'emprendedor optimista', N'Pendiente');
INSERT INTO trappiDb.dbo.PRUEBAADMISION (IDPRUEBA, ID_ASP, PUNTAJEPRUEBA, ACTITUDESPRUEBA, APTITUDESPRUEBA, APROBACIONPRUEBA) VALUES (10, 10, 15, N'alegre', N'innovador', N'Pendiente');
INSERT INTO trappiDb.dbo.PRUEBAADMISION (IDPRUEBA, ID_ASP, PUNTAJEPRUEBA, ACTITUDESPRUEBA, APTITUDESPRUEBA, APROBACIONPRUEBA) VALUES (11, 11, 18, N'alegre', N'emprendedor', N'Pendiente');
INSERT INTO trappiDb.dbo.PRUEBAADMISION (IDPRUEBA, ID_ASP, PUNTAJEPRUEBA, ACTITUDESPRUEBA, APTITUDESPRUEBA, APROBACIONPRUEBA) VALUES (12, 12, 18, N'alegre', N'emprendedor', N'Pendiente');
INSERT INTO trappiDb.dbo.PRUEBAADMISION (IDPRUEBA, ID_ASP, PUNTAJEPRUEBA, ACTITUDESPRUEBA, APTITUDESPRUEBA, APROBACIONPRUEBA) VALUES (13, 13, 19, N'alegre', N'emprendeor', N'Pendiente');
INSERT INTO trappiDb.dbo.PRUEBAADMISION (IDPRUEBA, ID_ASP, PUNTAJEPRUEBA, ACTITUDESPRUEBA, APTITUDESPRUEBA, APROBACIONPRUEBA) VALUES (8, 8, 16, N'alegre feliz ', N'emprendedor ', N'Pendiente');
INSERT INTO trappiDb.dbo.PRUEBAADMISION (IDPRUEBA, ID_ASP, PUNTAJEPRUEBA, ACTITUDESPRUEBA, APTITUDESPRUEBA, APROBACIONPRUEBA) VALUES (15, 15, 18, N'alegre feliz triste', N'emprendedor creativo', N'Pendiente');
INSERT INTO trappiDb.dbo.PRUEBAADMISION (IDPRUEBA, ID_ASP, PUNTAJEPRUEBA, ACTITUDESPRUEBA, APTITUDESPRUEBA, APROBACIONPRUEBA) VALUES (9, 9, 17, N'alegre feliz', N'emprendedor optimista', N'Pendiente');
INSERT INTO trappiDb.dbo.PRUEBAADMISION (IDPRUEBA, ID_ASP, PUNTAJEPRUEBA, ACTITUDESPRUEBA, APTITUDESPRUEBA, APROBACIONPRUEBA) VALUES (14, 14, 17, N'Feliz', N'Creativo', N'Pendiente');