package com.epn.trappi.gui.logistico;
import com.epn.trappi.models.logistico.ListaConductores;
import com.epn.trappi.models.logistico.ListaEntregas1;
import com.epn.trappi.models.logistico.ListaVehiculos;
import com.epn.trappi.models.logistico.Conductor;
import com.epn.trappi.models.logistico.Vehiculo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class EntregasActivas extends javax.swing.JPanel {
       
    public EntregasActivas() {
        
        
        initComponents();
        ListaVehiculos vehiculos = new ListaVehiculos();
        ListaConductores conductores = new ListaConductores();
        ListaEntregas1 entregas = new ListaEntregas1();      
        DefaultTableModel modelo = new DefaultTableModel();
        jTEntregasDatos.setModel(modelo);
        modelo.addColumn("ID_Entrega");
        modelo.addColumn("Cliente");
        modelo.addColumn("Conductor");
        modelo.addColumn("Vehiculo");
        modelo.addColumn("Destino");
        Object[] filas = new Object[5];
        String [] clientes= {"Christian Morán", "José Pallo", "Erick Mayorga", "Cristhian Muñoz", "Rommel Valdiviezo"};
        int idEntrega = 1;
        for(int i=0;i<5;i++){
            filas[0]=idEntrega;
            filas[1]=clientes[i];
            filas[2] = conductores.listaConductores.get(i).getNombre();
            filas[3] = vehiculos.vehiculos.get(i).getMatricula();
            filas[4] = entregas.entregas.get(i).getDestino();
            modelo.addRow(filas);
            idEntrega++;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTEntregasDatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPInformacionConductor = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAInformacionConductor = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1048, 660));

        jTEntregasDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID_Entrega", "Cliente", "Conductor", "Vehiculo", "Destino"
            }
        ));
        jTEntregasDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTEntregasDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTEntregasDatos);
        if (jTEntregasDatos.getColumnModel().getColumnCount() > 0) {
            jTEntregasDatos.getColumnModel().getColumn(4).setMinWidth(10);
        }

        jLabel1.setText("ENTREGAS ACTIVAS");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jLabel2.setText("RUTA");

        jLabel4.setText("Información asociada a la entrega:");

        jPInformacionConductor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTAInformacionConductor.setColumns(20);
        jTAInformacionConductor.setRows(5);
        jScrollPane2.setViewportView(jTAInformacionConductor);

        javax.swing.GroupLayout jPInformacionConductorLayout = new javax.swing.GroupLayout(jPInformacionConductor);
        jPInformacionConductor.setLayout(jPInformacionConductorLayout);
        jPInformacionConductorLayout.setHorizontalGroup(
            jPInformacionConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
        jPInformacionConductorLayout.setVerticalGroup(
            jPInformacionConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(44, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPInformacionConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jPInformacionConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTEntregasDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTEntregasDatosMouseClicked
        jTAInformacionConductor.setText("");
        int fila = jTEntregasDatos.getSelectedRow();
        String destino = (String)jTEntregasDatos.getValueAt(fila, 4);
        String nombreConductor = (String)jTEntregasDatos.getValueAt(fila,2);
        jTAInformacionConductor.setText("Nombre:\n" + nombreConductor + "\nDirección destino:\n" + destino);
    }//GEN-LAST:event_jTEntregasDatosMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPInformacionConductor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAInformacionConductor;
    private javax.swing.JTable jTEntregasDatos;
    // End of variables declaration//GEN-END:variables
}
