/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.epn.trappi.gui.logistico;

import com.epn.trappi.models.logistico.Estado;
import com.epn.trappi.models.logistico.Inhabilitado;
import com.epn.trappi.models.logistico.ListaMantenimientos;
import com.epn.trappi.models.logistico.ListaVehiculos;
import com.epn.trappi.models.logistico.Mantenimiento;
import com.epn.trappi.models.logistico.SolicitudMantenimiento;
import com.epn.trappi.models.logistico.Vehiculo;
import com.epn.trappi.models.logistico.servicios.ServicioDb;
import com.epn.trappi.models.logistico.servicios.ServicioDbMantenimiento;
import com.epn.trappi.models.logistico.servicios.ServicioDbSolicitudMantenimiento;
import com.epn.trappi.models.logistico.servicios.ServicioDbVehiculo;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexander
 */
public class FichasTecnicas extends javax.swing.JPanel {
    //ATRIBUTOS
    ServicioDb servicioDB;
    //METODOS
    public FichasTecnicas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMatriculaVehiculo = new javax.swing.JTextField();
        jTFidMantenimiento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDetallesMantenimiento = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVerificarVehiculo = new javax.swing.JTable();
        btnVerificarVehiculo = new javax.swing.JButton();
        btnRegistrarMantenimiento = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdMantenimiento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnRegistrarSolicitud = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTFidSolicitud = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtIdBien = new javax.swing.JTextField();
        btnVerificarMantenimiento = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTVerificarMantenimiento = new javax.swing.JTable();
        btnVerificarBien = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTVerificarBien = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Fichas técnicas");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(61, 57, 57), 2, true));
        jPanel2.setForeground(new java.awt.Color(61, 57, 57));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(61, 57, 57));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel7.setForeground(new java.awt.Color(61, 57, 57));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registrar Mantenimiento");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Filtros de búsqueda");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtMatriculaVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMatriculaVehiculo.setForeground(new java.awt.Color(61, 57, 57));
        txtMatriculaVehiculo.setText("PBP-2432");
        txtMatriculaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(txtMatriculaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 180, 30));

        jTFidMantenimiento.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTFidMantenimiento.setForeground(new java.awt.Color(61, 57, 57));
        jTFidMantenimiento.setText("123");
        jPanel2.add(jTFidMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 130, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(61, 57, 57));
        jLabel7.setText("ID Mantenimiento:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(61, 57, 57));
        jLabel8.setText("Matrícula del vehículo:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 30));

        txaDetallesMantenimiento.setColumns(20);
        txaDetallesMantenimiento.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txaDetallesMantenimiento.setForeground(new java.awt.Color(61, 57, 57));
        txaDetallesMantenimiento.setRows(5);
        jScrollPane1.setViewportView(txaDetallesMantenimiento);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 460, 70));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(61, 57, 57));
        jLabel6.setText("Detalles del mantenimiento:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, 30));

        jTableVerificarVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Matricula"
            }
        ));
        jScrollPane2.setViewportView(jTableVerificarVehiculo);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 360, 70));

        btnVerificarVehiculo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnVerificarVehiculo.setForeground(new java.awt.Color(61, 57, 57));
        btnVerificarVehiculo.setText("Verificar");
        btnVerificarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(btnVerificarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 360, 30));

        btnRegistrarMantenimiento.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnRegistrarMantenimiento.setForeground(new java.awt.Color(61, 57, 57));
        btnRegistrarMantenimiento.setText("Registrar");
        btnRegistrarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMantenimientoActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrarMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 150, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(61, 57, 57), 2, true));
        jPanel3.setForeground(new java.awt.Color(61, 57, 57));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(61, 57, 57));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel8.setForeground(new java.awt.Color(61, 57, 57));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registrar solicitud");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Filtros de búsqueda");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtIdMantenimiento.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtIdMantenimiento.setForeground(new java.awt.Color(61, 57, 57));
        txtIdMantenimiento.setText("123");
        jPanel3.add(txtIdMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 150, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(61, 57, 57));
        jLabel10.setText("ID Mantenimiento:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 30));

        btnRegistrarSolicitud.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnRegistrarSolicitud.setForeground(new java.awt.Color(61, 57, 57));
        btnRegistrarSolicitud.setText("Registrar");
        btnRegistrarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSolicitudActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistrarSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 146, 70));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(61, 57, 57));
        jLabel11.setText("ID solicitud:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 100, 30));

        jTFidSolicitud.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTFidSolicitud.setForeground(new java.awt.Color(61, 57, 57));
        jTFidSolicitud.setText("1");
        jPanel3.add(jTFidSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 150, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(61, 57, 57));
        jLabel12.setText("ID Bien:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 80, 30));

        txtIdBien.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtIdBien.setForeground(new java.awt.Color(61, 57, 57));
        txtIdBien.setText("8");
        jPanel3.add(txtIdBien, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 200, 30));

        btnVerificarMantenimiento.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnVerificarMantenimiento.setForeground(new java.awt.Color(61, 57, 57));
        btnVerificarMantenimiento.setText("Verificar");
        btnVerificarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarMantenimientoActionPerformed(evt);
            }
        });
        jPanel3.add(btnVerificarMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 300, 30));

        jTVerificarMantenimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Matricula"
            }
        ));
        jScrollPane3.setViewportView(jTVerificarMantenimiento);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 300, 100));

        btnVerificarBien.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnVerificarBien.setForeground(new java.awt.Color(61, 57, 57));
        btnVerificarBien.setText("Verificar");
        btnVerificarBien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarBienActionPerformed(evt);
            }
        });
        jPanel3.add(btnVerificarBien, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 300, 30));

        jTVerificarBien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Matricula"
            }
        ));
        jScrollPane4.setViewportView(jTVerificarBien);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 300, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(458, 458, 458))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(57, 57, 57)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarVehiculoActionPerformed
        ListaVehiculos vehiculos = new ListaVehiculos();
        servicioDB = new ServicioDbVehiculo();
        String valor = txtMatriculaVehiculo.getText();
        try {
            vehiculos.setVehiculos(servicioDB.obtenerElementosPorFiltro(ServicioDbVehiculo.MATRICULA, valor).getDatos());
            this.jTableVerificarVehiculo.setModel(vehiculos.mostrarLista());
        } catch (SQLException ex) {
            Logger.getLogger(FichasTecnicas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVerificarVehiculoActionPerformed

    private void btnVerificarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarMantenimientoActionPerformed
        ListaMantenimientos mantenimientos = new ListaMantenimientos();
        servicioDB = new ServicioDbMantenimiento();
        String valor = txtIdMantenimiento.getText();
        try {
            mantenimientos.setMantenimientos(servicioDB.obtenerElementosPorFiltro(ServicioDbMantenimiento.ID_MANTENIMIENTO, valor).getDatos());
            this.jTVerificarMantenimiento.setModel(mantenimientos.mostrarLista());
        } catch (SQLException ex) {
            Logger.getLogger(FichasTecnicas.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btnVerificarMantenimientoActionPerformed

    private void btnVerificarBienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarBienActionPerformed

    }//GEN-LAST:event_btnVerificarBienActionPerformed
    
    private String getFechaSistema(){
        String fechaActual="";
        Calendar fecha = new GregorianCalendar();
        int anio = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int hora = fecha.get(Calendar.HOUR_OF_DAY);
        int minuto = fecha.get(Calendar.MINUTE);
        int segundo = fecha.get(Calendar.SECOND);
        return anio + "-" + mes + "-" + dia + " " + hora + ":" + minuto + ":" + segundo ;
        
    }
    
    private void btnRegistrarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSolicitudActionPerformed
        /*
        servicioDB = new ServicioDbSolicitudMantenimiento();
        //Datos de la GUI
        String fechaSol = getFechaSistema(); 
        int numSolicitud = Integer.parseInt(jTFidSolicitud.getText());
        int identificadorBien = Integer.parseInt(txtIdBien.getText());
        int idMantenimiento = Integer.parseInt(txtIdMantenimiento.getText());
        System.out.println("fecha: " + fechaSol);
        //Instancia
        
        SolicitudMantenimiento solicitud = new SolicitudMantenimiento();
        solicitud.setId_Solicitud(numSolicitud);
        solicitud.setId_Bien(identificadorBien);
        solicitud.setId_Mantenimiento(idMantenimiento);
        solicitud.setEstado("En espera");
        solicitud.setFecha(fechaSol);
        System.out.println("SoLICITUD: " + solicitud.toString() );
        
        try {
            servicioDB.insertar(solicitud);
            JOptionPane.showMessageDialog(null, "Solicitud de mantenimiento ingresado exitosamente!");
        } catch (SQLException ex) {
            Logger.getLogger(FichasTecnicas.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
    }//GEN-LAST:event_btnRegistrarSolicitudActionPerformed

    private void btnRegistrarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMantenimientoActionPerformed

        Mantenimiento mantenimiento = new Mantenimiento(Integer.parseInt(jTFidMantenimiento.getText()),txtMatriculaVehiculo.getText(), txaDetallesMantenimiento.getText());
        try {
            servicioDB = new ServicioDbMantenimiento();
            servicioDB.insertar(mantenimiento);
            servicioDB = new ServicioDbVehiculo();
            ArrayList<Vehiculo> vehiculos = servicioDB.obtenerElementosPorFiltro(ServicioDbVehiculo.MATRICULA, txtMatriculaVehiculo.getText()).getDatos();
            Vehiculo vehiculo = vehiculos.get(0); //Como la matricula es unica entonces la lista tiene longitud 1
            vehiculo.setEstado(new Inhabilitado());
            servicioDB = new ServicioDbVehiculo();
            servicioDB.actualizar(vehiculo);
            JOptionPane.showMessageDialog(null, "Mantenimiento ingresado exitosamente!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Base de datos no disponible.");
        }
    }//GEN-LAST:event_btnRegistrarMantenimientoActionPerformed

    private void txtMatriculaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaVehiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarMantenimiento;
    private javax.swing.JButton btnRegistrarSolicitud;
    private javax.swing.JButton btnVerificarBien;
    private javax.swing.JButton btnVerificarMantenimiento;
    private javax.swing.JButton btnVerificarVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTFidMantenimiento;
    private javax.swing.JTextField jTFidSolicitud;
    private javax.swing.JTable jTVerificarBien;
    private javax.swing.JTable jTVerificarMantenimiento;
    private javax.swing.JTable jTableVerificarVehiculo;
    private javax.swing.JTextArea txaDetallesMantenimiento;
    private javax.swing.JTextField txtIdBien;
    private javax.swing.JTextField txtIdMantenimiento;
    private javax.swing.JTextField txtMatriculaVehiculo;
    // End of variables declaration//GEN-END:variables
}
