/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.epn.trappi.gui.logistico;


import com.epn.trappi.*;
import com.epn.trappi.models.logistico.ControlDisponibilidad;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
/**
 *
 * @author 
 */
public class Logistico_GUI extends javax.swing.JFrame {
    
    PanelControlDisponibilidad1 mapaDisponibilidad;
    //PanelEntregasActivas1 entregasActivas = new PanelEntregasActivas1();
    Entregas_en_Curso entregasCurso = new Entregas_en_Curso();
    FichasTecnicas fichasTecnicas = new FichasTecnicas();
    ListasVehiculos listasVehiculos = new ListasVehiculos();
    RegistroMantenimiento registroMantenimiento = new RegistroMantenimiento();
    RegistroEntregas registroEntregas = new RegistroEntregas();
    RegistrarVehiculo registroVehiculo= new RegistrarVehiculo();
    ActualizacionVehiculo actualizarVehiculo = new ActualizacionVehiculo();
    ControlDisponibilidad controlD;
    
    boolean bandera = false;

    public Logistico_GUI(){
        this.setSize(1366, 768);
        initComponents();
        //this.controlD = new ControlDisponibilidad();
        this.setLocationRelativeTo(null);
        mapaDisponibilidad= new PanelControlDisponibilidad1();
        configurarRadiosBotones(20);
        
    }

    public Logistico_GUI(ControlDisponibilidad control) {
        this.setSize(1366, 768);
        initComponents();
        this.controlD=control;
        mapaDisponibilidad= new PanelControlDisponibilidad1(control);
        this.setLocationRelativeTo(null);
        configurarRadiosBotones(20);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        panEntregas = new javax.swing.JPanel();
        botonControl = new javax.swing.JButton();
        botonRegistroEntregas = new javax.swing.JButton();
        botonEntregasActivas = new javax.swing.JButton();
        panEntregas1 = new javax.swing.JPanel();
        botonListaVehiculos = new javax.swing.JButton();
        botonActualizarVehiculo = new javax.swing.JButton();
        panEntregas2 = new javax.swing.JPanel();
        botonMantenimiento = new javax.swing.JButton();
        botonFichas = new javax.swing.JButton();
        btnMantenimientos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        botonRegistrarVehiculo = new javax.swing.JButton();
        jPEntregasActivasGUI = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(61, 57, 57));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.ibb.co/2yWzy05/Log-stica.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());

        btnVolver.setBackground(new java.awt.Color(255, 210, 28));
        btnVolver.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.ibb.co/TTsqKZW/left-arrow-1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnVolver.setText("   Regresar");
        btnVolver.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnVolver.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                moveMouseOnVolver(evt);
            }
        });
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseOnVolver(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnVehiculos.setBackground(new java.awt.Color(255, 210, 28));
        btnVehiculos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        btnVehiculos.setText("Vehículos");
        btnVehiculos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnVehiculos.setBorderPainted(false);
        btnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosActionPerformed(evt);
            }
        });

        panEntregas.setBackground(new java.awt.Color(61, 57, 57));

        botonControl.setBackground(new java.awt.Color(61, 57, 57));
        botonControl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        botonControl.setForeground(new java.awt.Color(255, 255, 255));
        botonControl.setText("Control disponibilidad");
        botonControl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonControl.setContentAreaFilled(false);
        botonControl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonControlMouseMoved(evt);
            }
        });
        botonControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonControlMouseExited(evt);
            }
        });
        botonControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonControlActionPerformed(evt);
            }
        });

        botonRegistroEntregas.setBackground(new java.awt.Color(61, 57, 57));
        botonRegistroEntregas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        botonRegistroEntregas.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistroEntregas.setText("Registro de entregas");
        botonRegistroEntregas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonRegistroEntregas.setContentAreaFilled(false);
        botonRegistroEntregas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonRegistroEntregasMouseMoved(evt);
            }
        });
        botonRegistroEntregas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistroEntregasMouseExited(evt);
            }
        });
        botonRegistroEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroEntregasActionPerformed(evt);
            }
        });

        botonEntregasActivas.setBackground(new java.awt.Color(61, 57, 57));
        botonEntregasActivas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        botonEntregasActivas.setForeground(new java.awt.Color(255, 255, 255));
        botonEntregasActivas.setText("Entregas activas");
        botonEntregasActivas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonEntregasActivas.setContentAreaFilled(false);
        botonEntregasActivas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonEntregasActivasMouseMoved(evt);
            }
        });
        botonEntregasActivas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEntregasActivasMouseExited(evt);
            }
        });
        botonEntregasActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntregasActivasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panEntregasLayout = new javax.swing.GroupLayout(panEntregas);
        panEntregas.setLayout(panEntregasLayout);
        panEntregasLayout.setHorizontalGroup(
            panEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEntregasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonRegistroEntregas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonControl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEntregasActivas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panEntregasLayout.setVerticalGroup(
            panEntregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEntregasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(botonControl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonRegistroEntregas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEntregasActivas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panEntregas1.setBackground(new java.awt.Color(61, 57, 57));

        botonListaVehiculos.setBackground(new java.awt.Color(61, 57, 57));
        botonListaVehiculos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        botonListaVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        botonListaVehiculos.setText("Lista de Vehículos");
        botonListaVehiculos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonListaVehiculos.setContentAreaFilled(false);
        botonListaVehiculos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                moveMouseOnListaV(evt);
            }
        });
        botonListaVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseOnListaV(evt);
            }
        });
        botonListaVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaVehiculosActionPerformed(evt);
            }
        });

        botonActualizarVehiculo.setBackground(new java.awt.Color(61, 57, 57));
        botonActualizarVehiculo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        botonActualizarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        botonActualizarVehiculo.setText("Actualizar Vehículo");
        botonActualizarVehiculo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonActualizarVehiculo.setContentAreaFilled(false);
        botonActualizarVehiculo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonActualizarVehiculomoveMouseOnListaV(evt);
            }
        });
        botonActualizarVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonActualizarVehiculoexitMouseOnListaV(evt);
            }
        });
        botonActualizarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panEntregas1Layout = new javax.swing.GroupLayout(panEntregas1);
        panEntregas1.setLayout(panEntregas1Layout);
        panEntregas1Layout.setHorizontalGroup(
            panEntregas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEntregas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEntregas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonListaVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonActualizarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panEntregas1Layout.setVerticalGroup(
            panEntregas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEntregas1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonListaVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(botonActualizarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panEntregas2.setBackground(new java.awt.Color(61, 57, 57));

        botonMantenimiento.setBackground(new java.awt.Color(61, 57, 57));
        botonMantenimiento.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        botonMantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        botonMantenimiento.setText("Historial");
        botonMantenimiento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonMantenimiento.setContentAreaFilled(false);
        botonMantenimiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                moveMouseOnMantenimiento(evt);
            }
        });
        botonMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseOnMantenimiento(evt);
            }
        });
        botonMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMantenimientoActionPerformed(evt);
            }
        });

        botonFichas.setBackground(new java.awt.Color(61, 57, 57));
        botonFichas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        botonFichas.setForeground(new java.awt.Color(255, 255, 255));
        botonFichas.setText("Solicitud y registro");
        botonFichas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonFichas.setContentAreaFilled(false);
        botonFichas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonFichasMouseMoved(evt);
            }
        });
        botonFichas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonFichasMouseExited(evt);
            }
        });
        botonFichas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFichasActionPerformed(evt);
            }
        });

        btnMantenimientos.setBackground(new java.awt.Color(255, 210, 28));
        btnMantenimientos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnMantenimientos.setForeground(new java.awt.Color(255, 255, 255));
        btnMantenimientos.setText("Mantenimientos");
        btnMantenimientos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMantenimientos.setBorderPainted(false);
        btnMantenimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panEntregas2Layout = new javax.swing.GroupLayout(panEntregas2);
        panEntregas2.setLayout(panEntregas2Layout);
        panEntregas2Layout.setHorizontalGroup(
            panEntregas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEntregas2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEntregas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonFichas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonMantenimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEntregas2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMantenimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panEntregas2Layout.setVerticalGroup(
            panEntregas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEntregas2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMantenimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonFichas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel3.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.ibb.co/Y31bVPv/icon.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel3.setText("jLabel3");

        jButton1.setBackground(new java.awt.Color(255, 210, 28));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Entregas");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botonRegistrarVehiculo.setBackground(new java.awt.Color(61, 57, 57));
        botonRegistrarVehiculo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        botonRegistrarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrarVehiculo.setText("Registrar Vehículo");
        botonRegistrarVehiculo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonRegistrarVehiculo.setContentAreaFilled(false);
        botonRegistrarVehiculo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonRegistrarVehiculomoveMouseOnListaV(evt);
            }
        });
        botonRegistrarVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistrarVehiculoexitMouseOnListaV(evt);
            }
        });
        botonRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17))
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panEntregas1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panEntregas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVehiculos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(botonRegistrarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(panEntregas2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panEntregas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panEntregas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonRegistrarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(panEntregas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 870));

        jPEntregasActivasGUI.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.ibb.co/phNx1zK/eliminar-1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.ibb.co/7yCS40c/minimizar-1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(937, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPEntregasActivasGUILayout = new javax.swing.GroupLayout(jPEntregasActivasGUI);
        jPEntregasActivasGUI.setLayout(jPEntregasActivasGUILayout);
        jPEntregasActivasGUILayout.setHorizontalGroup(
            jPEntregasActivasGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEntregasActivasGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPEntregasActivasGUILayout.setVerticalGroup(
            jPEntregasActivasGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEntregasActivasGUILayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 824, Short.MAX_VALUE))
        );

        jPanel3.add(jPEntregasActivasGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1050, 870));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void configurarRadiosBotones(int radio){
        this.btnVolver.setBorder(new RoundedBorder(24));
        this.btnVolver.setBorderPainted(true);
        this.btnVolver.setOpaque(false);
        this.btnVolver.setContentAreaFilled(false);
        this.btnVolver.setHorizontalAlignment(SwingConstants.LEFT);
        //
        this.botonRegistroEntregas.setBorder(new RoundedBorder(radio));
        this.botonRegistroEntregas.setOpaque(false);
        this.botonControl.setBorder(new RoundedBorder(radio));
        this.botonControl.setOpaque(false);
        this.botonEntregasActivas.setBorder(new RoundedBorder(radio));
        this.botonEntregasActivas.setOpaque(false);
        this.jButton1.setBorder(new RoundedBorder(radio));
        this.jButton1.setOpaque(false);
        this.botonFichas.setBorder(new RoundedBorder(radio));
        this.botonFichas.setOpaque(false);
        this.botonFichas.setContentAreaFilled(false);
        this.botonListaVehiculos.setBorder(new RoundedBorder(radio));
        this.botonListaVehiculos.setOpaque(false);
        this.botonMantenimiento.setBorder(new RoundedBorder(radio));
        this.botonMantenimiento.setOpaque(false);
        this.botonActualizarVehiculo.setBorder(new RoundedBorder(radio));
        this.botonActualizarVehiculo.setOpaque(false);
        
        this.botonRegistrarVehiculo.setBorder(new RoundedBorder(radio));
        this.botonRegistrarVehiculo.setOpaque(false);
    }
    private void configurarTransparencia(){
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (bandera ==false){
        panEntregas.setVisible(true);
        bandera = true;
    }
    
    else{
         panEntregas.setVisible(false);
        bandera = false;
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed
    //BOTONES REDONDEADOS
    public static class RoundedBorder implements Border {

    private int radius;


    RoundedBorder(int radius) {
        this.radius = radius;
    }


    @Override
    public Insets getBorderInsets(Component c) {
        return new Insets(this.radius+1, this.radius+1, this.radius+2, this.radius);
    }


    @Override
    public boolean isBorderOpaque() {
        return true;
    }


    @Override
    public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
        g.drawRoundRect(x, y, width-1, height-1, radius, radius);
    }
}
    private void botonControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonControlActionPerformed
       
        ocultarPaneles(this.mapaDisponibilidad);
        mapaDisponibilidad.setSize(1048,813);
        mapaDisponibilidad.llenarTablaVehiculos();
        jPEntregasActivasGUI.add(mapaDisponibilidad);
        jPEntregasActivasGUI.revalidate();
        jPEntregasActivasGUI.repaint();
        
    }//GEN-LAST:event_botonControlActionPerformed

    private void btnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVehiculosActionPerformed

    private void btnMantenimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMantenimientosActionPerformed

    private void botonEntregasActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntregasActivasActionPerformed

            ocultarPaneles(this.entregasCurso);
            entregasCurso.setSize(1048, 813);
            jPEntregasActivasGUI.add(entregasCurso);
            jPEntregasActivasGUI.revalidate();   
            jPEntregasActivasGUI.repaint();
            
    }//GEN-LAST:event_botonEntregasActivasActionPerformed
    //MOUSE EVENTS PARA LOS BOTONES
    private void moveMouseOnVolver(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMouseOnVolver
        
        Color c = new Color(255, 210, 28);
        this.btnVolver.setForeground(c);
    }//GEN-LAST:event_moveMouseOnVolver

    private void exitMouseOnVolver(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseOnVolver
        Color c = new Color(255, 255,255);
        this.btnVolver.setForeground(c);
    }//GEN-LAST:event_exitMouseOnVolver

    private void moveMouseOnMantenimiento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMouseOnMantenimiento
        Color c = new Color(255, 210, 28);
        this.botonMantenimiento.setForeground(c);
    }//GEN-LAST:event_moveMouseOnMantenimiento

    private void exitMouseOnMantenimiento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseOnMantenimiento
        Color c = new Color(255, 255,255);
        this.botonMantenimiento.setForeground(c);
    }//GEN-LAST:event_exitMouseOnMantenimiento

    private void moveMouseOnListaV(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMouseOnListaV
        Color c = new Color(255, 210, 28);
        this.botonListaVehiculos.setForeground(c);
    }//GEN-LAST:event_moveMouseOnListaV

    private void exitMouseOnListaV(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseOnListaV
        Color c = new Color(255, 255,255);
        this.botonListaVehiculos.setForeground(c);
    }//GEN-LAST:event_exitMouseOnListaV

    private void botonEntregasActivasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEntregasActivasMouseMoved
        Color c = new Color(255, 210, 28);
        this.botonEntregasActivas.setForeground(c);
    }//GEN-LAST:event_botonEntregasActivasMouseMoved

    private void botonEntregasActivasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEntregasActivasMouseExited
        Color c = new Color(255, 255,255);
        this.botonEntregasActivas.setForeground(c);
    }//GEN-LAST:event_botonEntregasActivasMouseExited

    private void botonRegistroEntregasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroEntregasMouseMoved
        Color c = new Color(255, 210, 28);
        this.botonRegistroEntregas.setForeground(c);
    }//GEN-LAST:event_botonRegistroEntregasMouseMoved

    private void botonRegistroEntregasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroEntregasMouseExited
        Color c = new Color(255, 255,255);
        this.botonRegistroEntregas.setForeground(c);
    }//GEN-LAST:event_botonRegistroEntregasMouseExited

    private void botonControlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonControlMouseMoved
        Color c = new Color(255, 210, 28);
        this.botonControl.setForeground(c);
    }//GEN-LAST:event_botonControlMouseMoved

    private void botonControlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonControlMouseExited
        Color c = new Color(255, 255,255);
        this.botonControl.setForeground(c);
    }//GEN-LAST:event_botonControlMouseExited

    private void botonRegistroEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroEntregasActionPerformed

        ocultarPaneles(this.registroEntregas);
        registroEntregas.setSize(1048,813);
        jPEntregasActivasGUI.add(registroEntregas);
        jPEntregasActivasGUI.revalidate();
        jPEntregasActivasGUI.repaint();
        
    }//GEN-LAST:event_botonRegistroEntregasActionPerformed

    private void botonFichasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFichasActionPerformed

        ocultarPaneles(this.fichasTecnicas);
        fichasTecnicas.setSize(1048, 813);
        jPEntregasActivasGUI.add(fichasTecnicas);
        jPEntregasActivasGUI.revalidate();
        jPEntregasActivasGUI.repaint();
    }//GEN-LAST:event_botonFichasActionPerformed

    private void botonListaVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaVehiculosActionPerformed

        ocultarPaneles(this.listasVehiculos);
        listasVehiculos.setSize(1048, 813);
        jPEntregasActivasGUI.add(listasVehiculos);
        jPEntregasActivasGUI.revalidate();
        jPEntregasActivasGUI.repaint();
    }//GEN-LAST:event_botonListaVehiculosActionPerformed

    private void botonMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMantenimientoActionPerformed

        ocultarPaneles(this.registroMantenimiento);
        registroMantenimiento.setSize(1048, 813);
        jPEntregasActivasGUI.add(registroMantenimiento);
        jPEntregasActivasGUI.revalidate();
        jPEntregasActivasGUI.repaint();
    }//GEN-LAST:event_botonMantenimientoActionPerformed

    private void botonFichasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonFichasMouseMoved
        Color c = new Color(255, 210, 28);
        this.botonFichas.setForeground(c);
    }//GEN-LAST:event_botonFichasMouseMoved

    private void botonFichasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonFichasMouseExited
        Color c = new Color(255, 255,255);
        this.botonFichas.setForeground(c);
    }//GEN-LAST:event_botonFichasMouseExited

    private void botonActualizarVehiculomoveMouseOnListaV(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarVehiculomoveMouseOnListaV
        Color c = new Color(255, 210, 28);
        this.botonActualizarVehiculo.setForeground(c);
    }//GEN-LAST:event_botonActualizarVehiculomoveMouseOnListaV

    private void botonActualizarVehiculoexitMouseOnListaV(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarVehiculoexitMouseOnListaV
        Color c = new Color(255, 255,255);
        this.botonActualizarVehiculo.setForeground(c);
    }//GEN-LAST:event_botonActualizarVehiculoexitMouseOnListaV

    private void botonActualizarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarVehiculoActionPerformed

        ocultarPaneles(this.actualizarVehiculo);
        actualizarVehiculo.setSize(1048, 770);
        jPEntregasActivasGUI.add(actualizarVehiculo);
        jPEntregasActivasGUI.revalidate();
        jPEntregasActivasGUI.repaint();
        
    }//GEN-LAST:event_botonActualizarVehiculoActionPerformed

    private void botonRegistrarVehiculomoveMouseOnListaV(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarVehiculomoveMouseOnListaV
        Color c = new Color(255, 210, 28);
        this.botonRegistrarVehiculo.setForeground(c);
    }//GEN-LAST:event_botonRegistrarVehiculomoveMouseOnListaV

    private void botonRegistrarVehiculoexitMouseOnListaV(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarVehiculoexitMouseOnListaV
        Color c = new Color(255, 255,255);
        this.botonRegistrarVehiculo.setForeground(c);
    }//GEN-LAST:event_botonRegistrarVehiculoexitMouseOnListaV

    private void botonRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarVehiculoActionPerformed
        
        ocultarPaneles(this.registroVehiculo);
        registroVehiculo.setSize(1048, 813);
        jPEntregasActivasGUI.add(registroVehiculo);
        jPEntregasActivasGUI.revalidate();
        jPEntregasActivasGUI.repaint();
        
    }//GEN-LAST:event_botonRegistrarVehiculoActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked
    //METODO PARA OCULTAR TODOS LOS PANELES EXCEPTO EL QUE SE INDIQUE
    private void ocultarPaneles(JPanel panel){
        mapaDisponibilidad.setVisible(panel.getClass().equals(mapaDisponibilidad.getClass()));
        registroEntregas.setVisible(panel.getClass().equals(registroEntregas.getClass()));
        entregasCurso.setVisible(panel.getClass().equals(entregasCurso.getClass()));
        fichasTecnicas.setVisible(panel.getClass().equals(fichasTecnicas.getClass()));
        listasVehiculos.setVisible(panel.getClass().equals(listasVehiculos.getClass()));
        registroMantenimiento.setVisible(panel.getClass().equals(registroMantenimiento.getClass()));
        actualizarVehiculo.setVisible(panel.getClass().equals(actualizarVehiculo.getClass()));
        registroVehiculo.setVisible(panel.getClass().equals(registroVehiculo.getClass()));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logistico_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logistico_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logistico_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logistico_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logistico_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarVehiculo;
    private javax.swing.JButton botonControl;
    private javax.swing.JButton botonEntregasActivas;
    private javax.swing.JButton botonFichas;
    private javax.swing.JButton botonListaVehiculos;
    private javax.swing.JButton botonMantenimiento;
    private javax.swing.JButton botonRegistrarVehiculo;
    private javax.swing.JButton botonRegistroEntregas;
    private javax.swing.JButton btnMantenimientos;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPEntregasActivasGUI;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panEntregas;
    private javax.swing.JPanel panEntregas1;
    private javax.swing.JPanel panEntregas2;
    // End of variables declaration//GEN-END:variables
}
