
package com.epn.trappi.gui.logistico;
import com.epn.trappi.models.logistico.ListaConductores;
import com.epn.trappi.models.logistico.ListaEntregas1;
import com.epn.trappi.models.logistico.ListaVehiculos;
import com.epn.trappi.models.logistico.Conductor;
import com.epn.trappi.models.logistico.Vehiculo;
import javax.swing.table.DefaultTableModel;

public class MapaDisponibilidad1 extends javax.swing.JPanel {

    public MapaDisponibilidad1() {
        initComponents();
        ListaVehiculos vehiculos = new ListaVehiculos();
        ListaConductores conductores = new ListaConductores();
        
        DefaultTableModel modelo = new DefaultTableModel();
        jTMatricula.setModel(modelo);
        modelo.addColumn("Matricula");
        Object[] filas = new Object[1];
        /*for(int i =0; i<vehiculos.vehiculos.size();i++){
            filas[i]=vehiculos.vehiculos.get(i).getMatricula();
        }*/
        //int i=0;
        for(Vehiculo a: vehiculos.vehiculos){
            filas[0]=a.getMatricula();
            //i++;
            modelo.addRow(filas);
        }
        //modelo.addRow(filas);
        
        //Mostrar Nombres de conductores------------------------ 
            DefaultTableModel modelo1 = new DefaultTableModel();
            jTNombres.setModel(modelo1);
            modelo1.addColumn("Nombre");
            for(Conductor a: conductores.listaConductores){
                filas[0]=a.getNombre();
                modelo1.addRow(filas);
            }
        //Fin de mostrar Nombres de Conductores----------------- 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTNombres = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTMatricula = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1048, 660));

        jTNombres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTNombres);

        jLabel1.setText("Conductores Disponibles");

        jTMatricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Matricula"
            }
        ));
        jScrollPane2.setViewportView(jTMatricula);

        jLabel5.setText("Vehiculos Disponibles");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTMatricula;
    private javax.swing.JTable jTNombres;
    // End of variables declaration//GEN-END:variables
}
