/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.epn.trappi.gui.logistico;

import com.epn.trappi.gui.logistico.Logistico_GUI.RoundedBorder;
import com.epn.trappi.models.logistico.Entrega;
import com.epn.trappi.models.logistico.ListaEntregas;
import com.epn.trappi.models.logistico.servicios.ServicioDb;
import com.epn.trappi.models.logistico.servicios.ServicioDbEntrega;
import static com.epn.trappi.models.logistico.servicios.ServicioVerificacion.*;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rommel Alexander
 */
public class RegistroEntregas extends javax.swing.JPanel {
    //ATRIBUTOS
    ListaEntregas entregas;
    RoundedBorder borde_circular;
    ServicioDb servicioDB;
    //METODOS
    public RegistroEntregas() {
        initComponents();
        //Instanciamos la lista de nuestro modelo y su servicio de base de datos
        this.entregas=new ListaEntregas();
        this.servicioDB = new ServicioDbEntrega();
        //Apariencia de la GUI
        this.botonBuscar.setBorder(new Logistico_GUI.RoundedBorder(20));
        this.botonBuscar.setBorderPainted(true);
        this.botonBuscar.setOpaque(false);
        this.botonBuscar.setContentAreaFilled(false);
        borde_circular = new RoundedBorder(24);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegistroEntregas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboBoxBusqueda = new javax.swing.JComboBox<>();
        campoAño = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        campoBusqueda = new javax.swing.JTextField();
        campoDia = new javax.swing.JTextField();
        campoRegistros = new javax.swing.JTextField();
        campoMes = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(96, 97, 101));
        jLabel1.setText("Registro de entregas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(238, 137, 117));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("5");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Entregas el día de hoy");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 100));

        jPanel4.setBackground(new java.awt.Color(121, 107, 200));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("31");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Entregas el día de ayer");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 220, 100));

        jPanel5.setBackground(new java.awt.Color(246, 70, 142));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 28)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("16");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Entregas el mes actual");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(34, 34, 34))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 240, 100));

        jPanel6.setBackground(new java.awt.Color(19, 155, 151));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 28)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("11");

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Entregas el mes anterior");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(34, 34, 34))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 230, 100));

        tablaRegistroEntregas.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        tablaRegistroEntregas.setForeground(new java.awt.Color(61, 57, 57));
        tablaRegistroEntregas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID_Entrega", "Cliente", "Conductor", "Vehiculo", "Destino"
            }
        ));
        tablaRegistroEntregas.setFocusable(false);
        tablaRegistroEntregas.setGridColor(new java.awt.Color(61, 57, 57));
        tablaRegistroEntregas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tablaRegistroEntregas.setOpaque(false);
        tablaRegistroEntregas.setRowHeight(30);
        tablaRegistroEntregas.setSelectionBackground(new java.awt.Color(61, 57, 57));
        tablaRegistroEntregas.getTableHeader().setReorderingAllowed(false);
        tablaRegistroEntregas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRegistroEntregasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaRegistroEntregas);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(219, 223, 228), 1, true));
        jPanel2.setForeground(new java.awt.Color(61, 57, 57));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Filtros de búsqueda");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(61, 57, 57));
        jLabel6.setText("Limitar la cantidad de registros:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, 30));

        comboBoxBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboBoxBusqueda.setForeground(new java.awt.Color(61, 57, 57));
        comboBoxBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Número de factura", "Número de matricula", "Id del conductor", "Estado de la entrega", "ID Entrega", "Fecha" }));
        comboBoxBusqueda.setBorder(null);
        jPanel2.add(comboBoxBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 170, 30));

        campoAño.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        campoAño.setForeground(new java.awt.Color(153, 153, 153));
        campoAño.setText("año");
        campoAño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoAñoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                campoAñoMouseExited(evt);
            }
        });
        jPanel2.add(campoAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 70, 30));

        botonBuscar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(61, 57, 57));
        botonBuscar.setText("Buscar");
        botonBuscar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonBuscarMouseMoved(evt);
            }
        });
        botonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonBuscarMouseExited(evt);
            }
        });
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 100, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(61, 57, 57));
        jLabel14.setText("Atributo de búsqueda:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        campoBusqueda.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        campoBusqueda.setForeground(new java.awt.Color(153, 153, 153));
        campoBusqueda.setText("Ingrese el valor de la columna que desea filtrar");
        campoBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoBusquedaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                campoBusquedaMouseExited(evt);
            }
        });
        campoBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBusquedaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoBusquedaKeyReleased(evt);
            }
        });
        jPanel2.add(campoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 370, 30));

        campoDia.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        campoDia.setForeground(new java.awt.Color(153, 153, 153));
        campoDia.setText("día");
        campoDia.setActionCommand("<Not Set>");
        campoDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoDiaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                campoDiaMouseExited(evt);
            }
        });
        campoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDiaActionPerformed(evt);
            }
        });
        jPanel2.add(campoDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 70, 30));

        campoRegistros.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        campoRegistros.setForeground(new java.awt.Color(153, 153, 153));
        campoRegistros.setText("20");
        campoRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoRegistrosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                campoRegistrosMouseExited(evt);
            }
        });
        jPanel2.add(campoRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 210, 30));

        campoMes.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        campoMes.setForeground(new java.awt.Color(153, 153, 153));
        campoMes.setText("mes");
        campoMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoMesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                campoMesMouseExited(evt);
            }
        });
        jPanel2.add(campoMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 70, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(61, 57, 57));
        jLabel15.setText("Filtrar por fecha:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(219, 223, 228), 1, true));
        jPanel7.setForeground(new java.awt.Color(61, 57, 57));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(34, 45, 50));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 45, 50));
        jLabel3.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.ibb.co/X4N1R0x/buscando-en-la-tierra.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel3.setText("  Búsqueda");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 14, 110, 30));

        jPanel8.setBackground(new java.awt.Color(96, 97, 101));
        jPanel8.setPreferredSize(new java.awt.Dimension(970, 5));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, -1));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaRegistroEntregasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRegistroEntregasMouseClicked

    }//GEN-LAST:event_tablaRegistroEntregasMouseClicked

    private void botonBuscarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseMoved
        Color c = new Color(255, 210, 28);
        this.botonBuscar.setForeground(c);
        
    }//GEN-LAST:event_botonBuscarMouseMoved

    private void botonBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseExited
        Color c = new Color(61,57,57);
        this.botonBuscar.setForeground(c);
    }//GEN-LAST:event_botonBuscarMouseExited

    private void campoBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBusquedaKeyPressed

    }//GEN-LAST:event_campoBusquedaKeyPressed

    private void campoBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBusquedaKeyReleased

    }//GEN-LAST:event_campoBusquedaKeyReleased

    private void campoBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoBusquedaMouseClicked
        campoBusqueda.setText("");
        campoBusqueda.setForeground(new Color(0,0,0));
        campoBusqueda.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 14));
    }//GEN-LAST:event_campoBusquedaMouseClicked

    private void campoBusquedaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoBusquedaMouseExited
        if (campoBusqueda.getText().length()==0){
            campoBusqueda.setForeground(new Color(153,153,153));
            campoBusqueda.setFont(new Font("Segoe UI Semibold", Font.ITALIC, 14));
            campoBusqueda.setText("Ingrese el valor de la columna que desea filtrar");
        }
    }//GEN-LAST:event_campoBusquedaMouseExited

    private void campoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDiaActionPerformed

    private void campoDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoDiaMouseClicked
        campoDia.setText("");
        campoDia.setForeground(new Color(0,0,0));
        campoDia.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 14));
    }//GEN-LAST:event_campoDiaMouseClicked

    private void campoDiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoDiaMouseExited
        if (campoDia.getText().length()==0){
            campoDia.setForeground(new Color(153,153,153));
            campoDia.setFont(new Font("Segoe UI Semibold", Font.ITALIC, 14));
            campoDia.setText("día");
        }
    }//GEN-LAST:event_campoDiaMouseExited

    private void campoMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoMesMouseClicked
        campoMes.setText("");
        campoMes.setForeground(new Color(0,0,0));
        campoMes.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 14));
    }//GEN-LAST:event_campoMesMouseClicked

    private void campoMesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoMesMouseExited
        if (campoMes.getText().length()==0){
            campoMes.setForeground(new Color(153,153,153));
            campoMes.setFont(new Font("Segoe UI Semibold", Font.ITALIC, 14));
            campoMes.setText("mes");
        }
    }//GEN-LAST:event_campoMesMouseExited

    private void campoAñoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoAñoMouseClicked
        campoAño.setText("");
        campoAño.setForeground(new Color(0,0,0));
        campoAño.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 14));
    }//GEN-LAST:event_campoAñoMouseClicked

    private void campoAñoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoAñoMouseExited
        if (campoAño.getText().length()==0){
            campoAño.setForeground(new Color(153,153,153));
            campoAño.setFont(new Font("Segoe UI Semibold", Font.ITALIC, 14));
            campoAño.setText("año");
        }
    }//GEN-LAST:event_campoAñoMouseExited

    private void campoRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoRegistrosMouseClicked
        campoRegistros.setText("");
        campoRegistros.setForeground(new Color(0,0,0));
        campoRegistros.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 14));
    }//GEN-LAST:event_campoRegistrosMouseClicked

    private void campoRegistrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoRegistrosMouseExited
        if (campoRegistros.getText().length()==0){
            campoRegistros.setForeground(new Color(153,153,153));
            campoRegistros.setFont(new Font("Segoe UI Semibold", Font.ITALIC, 14));
            campoRegistros.setText("20");
        }
    }//GEN-LAST:event_campoRegistrosMouseExited

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        int opcion = comboBoxBusqueda.getSelectedIndex();
        String campo_busqueda = campoBusqueda.getText();
        try{
        switch (opcion){
            case 0:
                
                entregas.setEntregas(servicioDB.obtenerElementos().getDatos());
                break;
                
            case 1:
                strErrores+=verificarID(campo_busqueda);
                if(!strErrores.equals(""))
                {
                    strErrores="Errores existentes:\n"+strErrores;
                    JOptionPane.showMessageDialog(null, strErrores , "Error al Buscar ID Factura" , JOptionPane.ERROR_MESSAGE);
                    strErrores="";
                    return;
                }else {
                entregas.setEntregas(servicioDB.obtenerElementosPorFiltro(ServicioDbEntrega.FACTURA,campo_busqueda).getDatos());
                break;
                }   
            case 2:
                strErrores+=verificarMatricula(campo_busqueda);
                if(!strErrores.equals(""))
                {
                    strErrores="Errores existentes:\n"+strErrores;
                    JOptionPane.showMessageDialog(null, strErrores , "Error al Buscar Matrícula" , JOptionPane.ERROR_MESSAGE);
                    strErrores="";
                    return;
                }else {
                entregas.setEntregas(servicioDB.obtenerElementosPorFiltro(ServicioDbEntrega.MATRICULA,campo_busqueda).getDatos());
                break;
                }
            case 3:
                strErrores+=verificarID(campo_busqueda);
                if(!strErrores.equals(""))
                {
                    strErrores="Errores existentes:\n"+strErrores;
                    JOptionPane.showMessageDialog(null, strErrores , "Error al Buscar ID Empleado" , JOptionPane.ERROR_MESSAGE);
                    strErrores="";
                    return;
                }else {
                entregas.setEntregas(servicioDB.obtenerElementosPorFiltro(ServicioDbEntrega.ID_EMPLEADO,campo_busqueda).getDatos());
                break;
                }
            case 4:
                strErrores+=verificarEstadoEntrega(campo_busqueda);
                if(!strErrores.equals(""))
                {
                    strErrores="Errores existentes:\n"+strErrores;
                    JOptionPane.showMessageDialog(null, strErrores , "Error al Buscar por Estado de Entrega" , JOptionPane.ERROR_MESSAGE);
                    strErrores="";
                    return;
                }else {
                entregas.setEntregas(servicioDB.obtenerElementosPorFiltro(ServicioDbEntrega.ESTADO,campo_busqueda).getDatos());
                break;
                }
            case 5:
                strErrores+=verificarID(campo_busqueda);
                if(!strErrores.equals(""))
                {
                    strErrores="Errores existentes:\n"+strErrores;
                    JOptionPane.showMessageDialog(null, strErrores , "Error al Buscar por ID Entrega" , JOptionPane.ERROR_MESSAGE);
                    strErrores="";
                    return;
                }else {
                entregas.setEntregas(servicioDB.obtenerElementosPorFiltro(ServicioDbEntrega.ID_ENTREGA,campo_busqueda).getDatos());
                break;
                }
            case 6:
                campo_busqueda="";
                String año=campoAño.getText().trim();
                String mes=campoMes.getText().trim();
                String dia=campoDia.getText().trim();
                if("".equals(mes) || "mes".equals(mes) || mes==null){
                    mes="99";
                }
                if("".equals(dia) || "dia".equals(dia) || dia==null){
                    dia="99";
                }
                campo_busqueda=año+"-"+mes+"-"+dia;
                strErrores+=verificarFecha(campo_busqueda);
                if(!strErrores.equals(""))
                {
                    strErrores="Errores existentes:\n"+strErrores;
                    JOptionPane.showMessageDialog(null, strErrores , "Error al Buscar por Fecha" , JOptionPane.ERROR_MESSAGE);
                    strErrores="";
                    return;
                }else {
                entregas.setEntregas(servicioDB.obtenerElementosPorFiltro(ServicioDbEntrega.FECHA,campo_busqueda).getDatos());
                break;
                }
        }
        int numero_registros=0;
        String numero = campoRegistros.getText();
        if(numero.length()!=0){
        try{
            //Si el numero de registros solicitados es mayor que los actuales entonces se considera el ultimo 
            numero_registros=Integer.parseInt(numero);
            if(numero_registros>entregas.getEntregas().size()){
                numero_registros=entregas.getEntregas().size();
            }
            ArrayList<Entrega> lista = new ArrayList<>();
            for(int puntero=0;puntero<numero_registros;puntero++){
                lista.add(entregas.getEntregas().get(puntero));
            }
            entregas.setEntregas(lista);
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Ingrese un valor entero para el número de registros");
        }}
        this.tablaRegistroEntregas.setModel(entregas.mostrarLista());
        }catch (SQLException e){
                JOptionPane.showMessageDialog(null,"Base de datos fuera de servicio");
                }
        
    }//GEN-LAST:event_botonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JTextField campoAño;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JTextField campoDia;
    private javax.swing.JTextField campoMes;
    private javax.swing.JTextField campoRegistros;
    private javax.swing.JComboBox<String> comboBoxBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaRegistroEntregas;
    // End of variables declaration//GEN-END:variables
    private String strErrores="";
}
