/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.epn.trappi.gui.rrhh;



import com.epn.trappi.models.rrhh.juanjo.ControlAsistencias;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.Border;


/**
 *
 * @author Javier Erazo
 */
public class ContratacionPrincipal extends javax.swing.JFrame {
    PanelContratos panelContratos = new PanelContratos();
    PanelContratarAspirante panelContratar = new PanelContratarAspirante();
    PanelRegistroAspirante panelRegistroAsp = new PanelRegistroAspirante();
    PanelEmpleado panelEmpleado = new PanelEmpleado(this);
    javax.swing.JFrame parent;
    public ControlAsistencias controlAsistencias;
    public void ocultarPaneles(JPanel panel){
        
        panelContratos.setVisible(panel.getClass().equals(panelContratos.getClass()));
        panelContratar.setVisible(panel.getClass().equals(panelContratar.getClass()));
        panelRegistroAsp.setVisible(panel.getClass().equals(panelRegistroAsp.getClass()));
        panelEmpleado.setVisible(panel.getClass().equals(panelEmpleado.getClass()));
    }
    
    private void configurarBotones(int radio){
        this.btnRegresar.setBorder(new RoundedBorder(24));
        this.btnRegresar.setBorderPainted(true);
        this.btnRegresar.setOpaque(false);
        this.btnRegresar.setContentAreaFilled(false);
        this.btnRegresar.setHorizontalAlignment(SwingConstants.CENTER);
        
        this.btnAspirantes.setBorder(new RoundedBorder(24));
        this.btnAspirantes.setBorderPainted(true);
        this.btnAspirantes.setOpaque(false);
        this.btnAspirantes.setContentAreaFilled(false);
        this.btnAspirantes.setHorizontalAlignment(SwingConstants.CENTER);
        this.btnContratar.setBorder(new RoundedBorder(24));
        this.btnContratar.setBorderPainted(true);
        this.btnContratar.setOpaque(false);
        this.btnContratar.setContentAreaFilled(false);
        this.btnContratar.setHorizontalAlignment(SwingConstants.CENTER);
        this.btnContratos.setBorder(new RoundedBorder(24));
        this.btnContratos.setBorderPainted(true);
        this.btnContratos.setOpaque(false);
        this.btnContratos.setContentAreaFilled(false);
        this.btnContratos.setHorizontalAlignment(SwingConstants.CENTER);
        this.btnEmpleados.setBorder(new RoundedBorder(24));
        this.btnEmpleados.setBorderPainted(true);
        this.btnEmpleados.setOpaque(false);
        this.btnEmpleados.setContentAreaFilled(false);
        this.btnEmpleados.setHorizontalAlignment(SwingConstants.CENTER);
        
    }


    public ContratacionPrincipal(ControlAsistencias control) {
        initComponents();
        this.controlAsistencias = control;
        this.setSize(1366, 768);
        this.setLocationRelativeTo(null);
        configurarBotones(20);

    }
    
    public ContratacionPrincipal(ControlAsistencias control, javax.swing.JFrame parent) {
        initComponents();
        this.parent = parent;
        this.controlAsistencias = control;
        this.setSize(1366, 768);
        this.setLocationRelativeTo(null);
        configurarBotones(20);

    }
    
    public ContratacionPrincipal() {
        initComponents();
        this.controlAsistencias = new ControlAsistencias();
        this.setSize(1366, 768);
        this.setLocationRelativeTo(null);
        configurarBotones(20);

    }

    public ControlAsistencias getControlAsistencias() {
        return controlAsistencias;
    }
    
    public static class RoundedBorder implements Border {

    private int radius;


    RoundedBorder(int radius) {
        this.radius = radius;
    }


    @Override
    public Insets getBorderInsets(Component c) {
        return new Insets(this.radius+1, this.radius+1, this.radius+2, this.radius);
    }


    @Override
    public boolean isBorderOpaque() {
        return true;
    }


    @Override
    public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
        g.drawRoundRect(x, y, width-1, height-1, radius, radius);
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnAspirantes = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnContratar = new javax.swing.JButton();
        btnContratos = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        PanelGeneralContratacion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(61, 57, 57));

        btnAspirantes.setBackground(new java.awt.Color(61, 57, 57));
        btnAspirantes.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnAspirantes.setForeground(new java.awt.Color(255, 255, 255));
        btnAspirantes.setText("Aspirantes");
        btnAspirantes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnAspirantesMouseMoved(evt);
            }
        });
        btnAspirantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAspirantesMouseExited(evt);
            }
        });
        btnAspirantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAspirantesActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(255, 210, 28));
        btnRegresar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnRegresarMouseMoved(evt);
            }
        });
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnContratar.setBackground(new java.awt.Color(61, 57, 57));
        btnContratar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnContratar.setForeground(new java.awt.Color(255, 255, 255));
        btnContratar.setText("Contratar");
        btnContratar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnContratarMouseMoved(evt);
            }
        });
        btnContratar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnContratarMouseExited(evt);
            }
        });
        btnContratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratarActionPerformed(evt);
            }
        });

        btnContratos.setBackground(new java.awt.Color(61, 57, 57));
        btnContratos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnContratos.setForeground(new java.awt.Color(255, 255, 255));
        btnContratos.setText("Contratos");
        btnContratos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnContratosMouseMoved(evt);
            }
        });
        btnContratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnContratosMouseExited(evt);
            }
        });
        btnContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratosActionPerformed(evt);
            }
        });

        btnEmpleados.setBackground(new java.awt.Color(61, 57, 57));
        btnEmpleados.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setText("Empleados");
        btnEmpleados.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnEmpleadosMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEmpleadosMouseMoved(evt);
            }
        });
        btnEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmpleadosMouseExited(evt);
            }
        });
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoRRHH.PNG"))); // NOI18N

        jButton3.setBackground(new java.awt.Color(255, 210, 28));
        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Contratación");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnContratos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnContratar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAspirantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAspirantes, btnContratar, btnContratos, btnEmpleados});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnAspirantes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnContratar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAspirantes, btnContratar, btnContratos, btnEmpleados});

        PanelGeneralContratacion.setPreferredSize(new java.awt.Dimension(830, 660));

        javax.swing.GroupLayout PanelGeneralContratacionLayout = new javax.swing.GroupLayout(PanelGeneralContratacion);
        PanelGeneralContratacion.setLayout(PanelGeneralContratacionLayout);
        PanelGeneralContratacionLayout.setHorizontalGroup(
            PanelGeneralContratacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 832, Short.MAX_VALUE)
        );
        PanelGeneralContratacionLayout.setVerticalGroup(
            PanelGeneralContratacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelGeneralContratacion, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(PanelGeneralContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAspirantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAspirantesActionPerformed
        ocultarPaneles(panelRegistroAsp);
        panelRegistroAsp.setSize(1000,800);
        PanelGeneralContratacion.add(panelRegistroAsp);
        PanelGeneralContratacion.revalidate();
        PanelGeneralContratacion.repaint();
    }//GEN-LAST:event_btnAspirantesActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        this.parent.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnContratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratarActionPerformed
        ocultarPaneles(panelContratar);
        panelContratar.setSize(1000,800);
        PanelGeneralContratacion.add(panelContratar);
        PanelGeneralContratacion.revalidate();
        PanelGeneralContratacion.repaint();
    }//GEN-LAST:event_btnContratarActionPerformed

    private void btnContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratosActionPerformed
        ocultarPaneles(panelContratos);
        panelContratos.setSize(1000,800);
        PanelGeneralContratacion.add(panelContratos);
        PanelGeneralContratacion.revalidate();
        PanelGeneralContratacion.repaint();
    }//GEN-LAST:event_btnContratosActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        ocultarPaneles(panelEmpleado);
        panelEmpleado.setSize(1000, 800);
        PanelGeneralContratacion.add(panelEmpleado);
        PanelGeneralContratacion.revalidate();
        PanelGeneralContratacion.repaint();
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnEmpleadosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseMoved
        Color c = new Color(255, 210, 28);
        this.btnEmpleados.setForeground(c);
    }//GEN-LAST:event_btnEmpleadosMouseMoved

    private void btnEmpleadosMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseDragged
       
    }//GEN-LAST:event_btnEmpleadosMouseDragged

    private void btnEmpleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseExited
        Color c = new Color(255, 255,255);
        this.btnEmpleados.setForeground(c);
    }//GEN-LAST:event_btnEmpleadosMouseExited

    private void btnAspirantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAspirantesMouseExited
        Color c = new Color(255, 255,255);
        this.btnAspirantes.setForeground(c);
    }//GEN-LAST:event_btnAspirantesMouseExited

    private void btnAspirantesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAspirantesMouseMoved
        Color c = new Color(255, 210, 28);
        this.btnAspirantes.setForeground(c);
    }//GEN-LAST:event_btnAspirantesMouseMoved

    private void btnContratarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContratarMouseMoved
        Color c = new Color(255, 210, 28);
        this.btnContratar.setForeground(c);
    }//GEN-LAST:event_btnContratarMouseMoved

    private void btnContratarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContratarMouseExited
        Color c = new Color(255, 255,255);
        this.btnContratar.setForeground(c);
    }//GEN-LAST:event_btnContratarMouseExited

    private void btnContratosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContratosMouseExited
        Color c = new Color(255, 255,255);
        this.btnContratos.setForeground(c);
    }//GEN-LAST:event_btnContratosMouseExited

    private void btnContratosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContratosMouseMoved
        Color c = new Color(255, 210, 28);
        this.btnContratos.setForeground(c);
    }//GEN-LAST:event_btnContratosMouseMoved

    private void btnRegresarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseMoved
        Color c = new Color(255, 210, 28);
        this.btnRegresar.setForeground(c);
    }//GEN-LAST:event_btnRegresarMouseMoved

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        Color c = new Color(255, 255,255);
        this.btnRegresar.setForeground(c);
    }//GEN-LAST:event_btnRegresarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContratacionPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContratacionPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContratacionPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContratacionPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContratacionPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGeneralContratacion;
    private javax.swing.JButton btnAspirantes;
    private javax.swing.JButton btnContratar;
    private javax.swing.JButton btnContratos;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
