/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.epn.trappi.gui.rrhh;


import com.epn.trappi.*;
import com.epn.trappi.models.rrhh.Fecha;
import com.epn.trappi.models.rrhh.contratacion.Aspirante;
import com.epn.trappi.models.rrhh.contratacion.Contrato;
import com.epn.trappi.models.rrhh.contratacion.PruebaAdmision;
import com.epn.trappi.models.rrhh.juanjo.Administrativo;
import com.epn.trappi.models.rrhh.juanjo.Conductor;
import com.epn.trappi.models.rrhh.juanjo.Empleado;
import com.epn.trappi.models.rrhh.listas.Lista;
import com.epn.trappi.models.rrhh.listas.ListaAspirantes;
import com.epn.trappi.models.rrhh.listas.ListaContratos;
import com.epn.trappi.models.rrhh.listas.ListaEmpleados;
import com.epn.trappi.models.rrhh.listas.ListaPruebasAdmision;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author stali
 */
public class ContratarAspirante extends javax.swing.JFrame {
    private void listarAspirantes(){
        Lista listaAspirantes = new ListaAspirantes();
        Aspirante[] aspirantes = (Aspirante[]) listaAspirantes.obtenerTodos();
        ListaPruebasAdmision listaPruebas = new ListaPruebasAdmision();
        DefaultTableModel model = (DefaultTableModel) jTableAspirantesAptos.getModel();
        model.setRowCount(0);
        
        for (Aspirante asp: aspirantes){
            Vector v = new Vector();
            PruebaAdmision prueba = new PruebaAdmision();
            prueba = listaPruebas.buscarUno(asp.getCedula());
            if (prueba != null){
                v.add(asp.getNombre());
                v.add(asp.getApellidos());
                v.add(asp.getTelefono());
                v.add(asp.getCedula());
                v.add(asp.getCargoAspirante());
                v.add(prueba.getActitudes());
                v.add(prueba.getAptitudes());
                v.add(prueba.getPuntaje());
                model.addRow(v); 
            } else {
                continue;
            }
            
            jTableAspirantesAptos.setModel(model);
        }
    }
    public ContratarAspirante() {
        initComponents();
        jBtnContratar.setEnabled(false);
        jTextContratoFechaInicioDia.setEnabled(false);
        jTextContratoFechaInicioMes.setEnabled(false);
        jTextContratoFechaInicioAno.setEnabled(false);
        jTextContratoFechaFinDia.setEnabled(false);
        jTextContratoFechaFinMes.setEnabled(false);
        jTextContratoFechaFinAno.setEnabled(false);
        jCmbContratoTipoEmpleado.setEnabled(false);
        jTextContratoNumCuenta.setEnabled(false);
        jTextContratoSueldo.setEnabled(false);
        jTextContratoDepto.setEnabled(false);
        jTextContratoBanco.setEnabled(false);
        jTextContratoCargo.setEnabled(false);
        jCmbContratoTipoEmpleado.setEnabled(false);
        jCmbContratoTipo.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpCopiaCedula = new javax.swing.ButtonGroup();
        btnGrpCopiaTitulo = new javax.swing.ButtonGroup();
        btnGrpREvisionMedica = new javax.swing.ButtonGroup();
        btnGrpSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PanelAspirante = new javax.swing.JPanel();
        jBtnBuscarAspirantes = new javax.swing.JButton();
        jBtnNuevoContrato = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAspirantesAptos = new javax.swing.JTable();
        jTextContratoFechaInicioDia = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jCmbContratoTipoEmpleado = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextContratoPuntaje = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextContratoBanco = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextContratoSueldo = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextContratoDepto = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextContratoCargo = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        rdbtFemenino = new javax.swing.JRadioButton();
        rdbtMasculino = new javax.swing.JRadioButton();
        jBtnContratar = new javax.swing.JButton();
        jTextContratoNumCuenta = new javax.swing.JTextField();
        jTextContratoAptitudes = new javax.swing.JTextField();
        jTextContratoActitudes = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jCmbContratoTipo = new javax.swing.JComboBox<>();
        jBtnBuscarAspirantes1 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jTextContratoFechaInicioMes = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextContratoFechaInicioAno = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextContratoFechaInicio3 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextContratoFechaInicio4 = new javax.swing.JTextField();
        jTextContratoFechaInicio5 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextContratoFechaFinAno = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextContratoFechaFinMes = new javax.swing.JTextField();
        jTextContratoFechaFinDia = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGOtrappi.jpeg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton4.setText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RECURSOS HUMANOS");

        jButton1.setBackground(new java.awt.Color(204, 153, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Aspirantes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(204, 153, 0));
        btnVolver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(51, 51, 51));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 153, 0));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 51));
        jButton6.setText("Contratos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 153, 0));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 51, 51));
        jButton7.setText("Contratación");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 153, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Empleados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelAspirante.setBackground(new java.awt.Color(255, 255, 255));
        PanelAspirante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnBuscarAspirantes.setBackground(new java.awt.Color(0, 153, 0));
        jBtnBuscarAspirantes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnBuscarAspirantes.setForeground(new java.awt.Color(240, 240, 241));
        jBtnBuscarAspirantes.setText("Buscar");
        jBtnBuscarAspirantes.setBorderPainted(false);
        jBtnBuscarAspirantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarAspirantesActionPerformed(evt);
            }
        });
        PanelAspirante.add(jBtnBuscarAspirantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jBtnNuevoContrato.setBackground(new java.awt.Color(38, 112, 171));
        jBtnNuevoContrato.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnNuevoContrato.setForeground(new java.awt.Color(240, 240, 241));
        jBtnNuevoContrato.setText("Nuevo");
        jBtnNuevoContrato.setBorderPainted(false);
        jBtnNuevoContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoContratoActionPerformed(evt);
            }
        });
        PanelAspirante.add(jBtnNuevoContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 99, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Usted está a punto de contratar un nuevo empleado, ingrese actitudes, aptitudes y puntaje deseado para mostrar sus opciones.");
        PanelAspirante.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTableAspirantesAptos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Teléfono", "Cédula", "Cargo", "Actitudes", "Aptitudes", "Puntaje"
            }
        ));
        jScrollPane1.setViewportView(jTableAspirantesAptos);

        PanelAspirante.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 840, 250));

        jTextContratoFechaInicioDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContratoFechaInicioDiaActionPerformed(evt);
            }
        });
        jTextContratoFechaInicioDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContratoFechaInicioDiaKeyTyped(evt);
            }
        });
        PanelAspirante.add(jTextContratoFechaInicioDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 30, 28));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Tipo:");
        PanelAspirante.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Fecha Fin:");
        PanelAspirante.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jCmbContratoTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "Conductor", "Administrativo" }));
        jCmbContratoTipoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbContratoTipoEmpleadoActionPerformed(evt);
            }
        });
        PanelAspirante.add(jCmbContratoTipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 110, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Datos Contrato");
        PanelAspirante.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Fecha Inicio:");
        PanelAspirante.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Actitudes");
        PanelAspirante.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jTextContratoPuntaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContratoPuntajeActionPerformed(evt);
            }
        });
        jTextContratoPuntaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContratoPuntajeKeyTyped(evt);
            }
        });
        PanelAspirante.add(jTextContratoPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 90, 28));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Puntaje");
        PanelAspirante.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, -1, -1));

        jTextContratoBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContratoBancoActionPerformed(evt);
            }
        });
        jTextContratoBanco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContratoBancoKeyTyped(evt);
            }
        });
        PanelAspirante.add(jTextContratoBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 250, 28));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Sueldo($)");
        PanelAspirante.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 60, -1));

        jTextContratoSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContratoSueldoActionPerformed(evt);
            }
        });
        jTextContratoSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContratoSueldoKeyTyped(evt);
            }
        });
        PanelAspirante.add(jTextContratoSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 160, 28));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Depto.");
        PanelAspirante.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 50, -1));

        jTextContratoDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContratoDeptoActionPerformed(evt);
            }
        });
        jTextContratoDepto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContratoDeptoKeyTyped(evt);
            }
        });
        PanelAspirante.add(jTextContratoDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 160, 28));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Cargo");
        PanelAspirante.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        jTextContratoCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContratoCargoActionPerformed(evt);
            }
        });
        jTextContratoCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContratoCargoKeyTyped(evt);
            }
        });
        PanelAspirante.add(jTextContratoCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 250, 28));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Sexo");
        PanelAspirante.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        btnGrpSexo.add(rdbtFemenino);
        rdbtFemenino.setText("F");
        PanelAspirante.add(rdbtFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, -1, -1));

        btnGrpSexo.add(rdbtMasculino);
        rdbtMasculino.setText("M");
        rdbtMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtMasculinoActionPerformed(evt);
            }
        });
        PanelAspirante.add(rdbtMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, -1, -1));

        jBtnContratar.setBackground(new java.awt.Color(0, 153, 153));
        jBtnContratar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnContratar.setForeground(new java.awt.Color(240, 240, 241));
        jBtnContratar.setText("Contratar");
        jBtnContratar.setBorderPainted(false);
        jBtnContratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnContratarActionPerformed(evt);
            }
        });
        PanelAspirante.add(jBtnContratar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jTextContratoNumCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContratoNumCuentaActionPerformed(evt);
            }
        });
        jTextContratoNumCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContratoNumCuentaKeyTyped(evt);
            }
        });
        PanelAspirante.add(jTextContratoNumCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 160, 28));

        jTextContratoAptitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContratoAptitudesActionPerformed(evt);
            }
        });
        jTextContratoAptitudes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContratoAptitudesKeyTyped(evt);
            }
        });
        PanelAspirante.add(jTextContratoAptitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 180, 28));

        jTextContratoActitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContratoActitudesActionPerformed(evt);
            }
        });
        jTextContratoActitudes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContratoActitudesKeyTyped(evt);
            }
        });
        PanelAspirante.add(jTextContratoActitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 190, 28));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Tipo");
        PanelAspirante.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Banco");
        PanelAspirante.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Aptitudes");
        PanelAspirante.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("DD");
        PanelAspirante.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jCmbContratoTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "Fijo", "Temporal", "Temporada" }));
        jCmbContratoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbContratoTipoActionPerformed(evt);
            }
        });
        PanelAspirante.add(jCmbContratoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 110, 30));

        jBtnBuscarAspirantes1.setBackground(new java.awt.Color(0, 153, 153));
        jBtnBuscarAspirantes1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnBuscarAspirantes1.setForeground(new java.awt.Color(240, 240, 241));
        jBtnBuscarAspirantes1.setText("...");
        jBtnBuscarAspirantes1.setBorderPainted(false);
        jBtnBuscarAspirantes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarAspirantes1ActionPerformed(evt);
            }
        });
        PanelAspirante.add(jBtnBuscarAspirantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 40, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("# Cuenta");
        PanelAspirante.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 60, -1));

        jTextContratoFechaInicioMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContratoFechaInicioMesActionPerformed(evt);
            }
        });
        jTextContratoFechaInicioMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContratoFechaInicioMesKeyTyped(evt);
            }
        });
        PanelAspirante.add(jTextContratoFechaInicioMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 30, 28));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("MM");
        PanelAspirante.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jTextContratoFechaInicioAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContratoFechaInicioAnoActionPerformed(evt);
            }
        });
        jTextContratoFechaInicioAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContratoFechaInicioAnoKeyTyped(evt);
            }
        });
        PanelAspirante.add(jTextContratoFechaInicioAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 50, 28));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("AAA");
        PanelAspirante.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jTextContratoFechaInicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContratoFechaInicio3ActionPerformed(evt);
            }
        });
        jTextContratoFechaInicio3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContratoFechaInicio3KeyTyped(evt);
            }
        });
        PanelAspirante.add(jTextContratoFechaInicio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 50, 28));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("AAA");
        PanelAspirante.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jTextContratoFechaInicio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContratoFechaInicio4ActionPerformed(evt);
            }
        });
        jTextContratoFechaInicio4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContratoFechaInicio4KeyTyped(evt);
            }
        });
        PanelAspirante.add(jTextContratoFechaInicio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 30, 28));

        jTextContratoFechaInicio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContratoFechaInicio5ActionPerformed(evt);
            }
        });
        jTextContratoFechaInicio5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContratoFechaInicio5KeyTyped(evt);
            }
        });
        PanelAspirante.add(jTextContratoFechaInicio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 30, 28));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("DD");
        PanelAspirante.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jTextContratoFechaFinAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContratoFechaFinAnoActionPerformed(evt);
            }
        });
        jTextContratoFechaFinAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContratoFechaFinAnoKeyTyped(evt);
            }
        });
        PanelAspirante.add(jTextContratoFechaFinAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 50, 28));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("AAA");
        PanelAspirante.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jTextContratoFechaFinMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContratoFechaFinMesActionPerformed(evt);
            }
        });
        jTextContratoFechaFinMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContratoFechaFinMesKeyTyped(evt);
            }
        });
        PanelAspirante.add(jTextContratoFechaFinMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 30, 28));

        jTextContratoFechaFinDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContratoFechaFinDiaActionPerformed(evt);
            }
        });
        jTextContratoFechaFinDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContratoFechaFinDiaKeyTyped(evt);
            }
        });
        PanelAspirante.add(jTextContratoFechaFinDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 30, 28));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText("DD");
        PanelAspirante.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("MM");
        PanelAspirante.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelAspirante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelAspirante, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new RegistroAspirante().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        new PANTALLA_PRINCIPAL().setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jBtnNuevoContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoContratoActionPerformed
        jBtnContratar.setEnabled(true);
        jTextContratoFechaInicioDia.setEnabled(true);
        jTextContratoFechaInicioMes.setEnabled(true);
        jTextContratoFechaInicioAno.setEnabled(true);
        jTextContratoFechaFinDia.setEnabled(true);
        jTextContratoFechaFinMes.setEnabled(true);
        jTextContratoFechaFinAno.setEnabled(true);
        jCmbContratoTipoEmpleado.setEnabled(true);
        jTextContratoNumCuenta.setEnabled(true);
        jTextContratoSueldo.setEnabled(true);
        jTextContratoDepto.setEnabled(true);
        jTextContratoBanco.setEnabled(true);
        jTextContratoCargo.setEnabled(true);
        jCmbContratoTipoEmpleado.setEnabled(true);
        jCmbContratoTipo.setEnabled(true);
    }//GEN-LAST:event_jBtnNuevoContratoActionPerformed

    private void jBtnBuscarAspirantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarAspirantesActionPerformed
        PruebaAdmision pruebas = new PruebaAdmision();
        ArrayList <Aspirante> aspirantesAptos = new ArrayList<>();
        aspirantesAptos = pruebas.obtenerAspirantesAptos(jTextContratoActitudes.getText(), jTextContratoAptitudes.getText(), Integer.parseInt(jTextContratoPuntaje.getText()));
        if (aspirantesAptos.size() > 0){
           
            ListaPruebasAdmision listaPruebas = new ListaPruebasAdmision();
            DefaultTableModel model = (DefaultTableModel) jTableAspirantesAptos.getModel();
            model.setRowCount(0);

            for (Aspirante asp: aspirantesAptos){
                Vector v = new Vector();
                PruebaAdmision prueba = new PruebaAdmision();
                prueba = listaPruebas.buscarUno(asp.getCedula());
                if (prueba != null){
                    v.add(asp.getNombre());
                    v.add(asp.getApellidos());
                    v.add(asp.getTelefono());
                    v.add(asp.getCedula());
                    v.add(asp.getCargoAspirante());
                    v.add(prueba.getActitudes());
                    v.add(prueba.getAptitudes());
                    v.add(prueba.getPuntaje());
                    model.addRow(v); 
                } else {
                    continue;
                }

                jTableAspirantesAptos.setModel(model);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No existen aspirantes con esos resultados");
        }
        
        
    }//GEN-LAST:event_jBtnBuscarAspirantesActionPerformed

    private void jTextContratoFechaInicioDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContratoFechaInicioDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaInicioDiaActionPerformed

    private void jTextContratoFechaInicioDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContratoFechaInicioDiaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaInicioDiaKeyTyped

    private void jCmbContratoTipoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbContratoTipoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbContratoTipoEmpleadoActionPerformed

    private void jTextContratoPuntajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContratoPuntajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoPuntajeActionPerformed

    private void jTextContratoPuntajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContratoPuntajeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoPuntajeKeyTyped

    private void jTextContratoBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContratoBancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoBancoActionPerformed

    private void jTextContratoBancoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContratoBancoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoBancoKeyTyped

    private void jTextContratoSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContratoSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoSueldoActionPerformed

    private void jTextContratoSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContratoSueldoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoSueldoKeyTyped

    private void jTextContratoDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContratoDeptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoDeptoActionPerformed

    private void jTextContratoDeptoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContratoDeptoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoDeptoKeyTyped

    private void jTextContratoCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContratoCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoCargoActionPerformed

    private void jTextContratoCargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContratoCargoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoCargoKeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
        new Contratos().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.setVisible(false);
        new ContratarAspirante().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new EmpleadoGui().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rdbtMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtMasculinoActionPerformed

    private void jBtnContratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnContratarActionPerformed
        //Obtenemos las datos del aspirante
        DefaultTableModel model = (DefaultTableModel) jTableAspirantesAptos.getModel();
        int selected = jTableAspirantesAptos.getSelectedRow();
        if (selected >=0) {
            String nombre = (String) model.getValueAt(selected, 0);
            String apellido = (String) model.getValueAt(selected, 1);

            String cedula = (String) model.getValueAt(selected, 3);
            String cargo = (String) model.getValueAt(selected, 4);
            String depto = jTextContratoDepto.getText();
            String numCuenta = jTextContratoNumCuenta.getText();
            String banco = jTextContratoBanco.getText();
            String valorSueldo = jTextContratoSueldo.getText();
            rdbtMasculino.setActionCommand("M");
            rdbtFemenino.setActionCommand("F");
            char sexo = btnGrpSexo.getSelection().getActionCommand().charAt(0);
            String tipoContrato = (String) jCmbContratoTipo.getSelectedItem();
            String tipoEmpleado = (String) jCmbContratoTipoEmpleado.getSelectedItem();
            String estadoEmp = "Activo";
            
            //Se realiza el registro del empleado en la base de datos 
            Lista listaEmpleado = new ListaEmpleados();
            Empleado nuevoEmpleado = null;
            if (tipoEmpleado.equalsIgnoreCase("conductor")){
                int idNuevoEmp = listaEmpleado.obtenerTodos().length + 1;
                nuevoEmpleado = new Conductor(idNuevoEmp, nombre, apellido, cedula, cargo, depto, numCuenta, banco, valorSueldo, estadoEmp, sexo);
                listaEmpleado.agregar(nuevoEmpleado);
            } else if (tipoEmpleado.equalsIgnoreCase("administrativo")) {
                int idNuevoEmp = listaEmpleado.obtenerTodos().length + 1;
                nuevoEmpleado = new Administrativo(idNuevoEmp, nombre, apellido, cedula, cargo, depto, numCuenta, banco, valorSueldo, estadoEmp, sexo);
                listaEmpleado.agregar(nuevoEmpleado);
                JOptionPane.showMessageDialog(null, "El Empleado Administrativo se contrató con éxito");
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione el tipo de empleado");
            }
            if (nuevoEmpleado != null){
                //Se procede a registrarContrato el contrato
                Fecha fechaInicio = new Fecha(Integer.parseInt(jTextContratoFechaInicioDia.getText()),
                        Integer.parseInt(jTextContratoFechaInicioMes.getText()),
                        Integer.parseInt(jTextContratoFechaInicioAno.getText()));
                Fecha fechaFin = new Fecha(Integer.parseInt(jTextContratoFechaFinDia.getText()),
                        Integer.parseInt(jTextContratoFechaFinMes.getText()),
                        Integer.parseInt(jTextContratoFechaFinAno.getText()));
                Contrato contrato = new Contrato();
                contrato.registrarContrato(fechaInicio, fechaFin, tipoContrato, valorSueldo, cedula);               
                JOptionPane.showMessageDialog(null, "El Empleado se contrató con éxito");
            }
                
            

        } else {
            JOptionPane.showMessageDialog(null, "Debe buscar y seleccionar el aspirante a contratar...");
        }
        
    }//GEN-LAST:event_jBtnContratarActionPerformed

    private void jTextContratoNumCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContratoNumCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoNumCuentaActionPerformed

    private void jTextContratoNumCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContratoNumCuentaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoNumCuentaKeyTyped

    private void jTextContratoAptitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContratoAptitudesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoAptitudesActionPerformed

    private void jTextContratoAptitudesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContratoAptitudesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoAptitudesKeyTyped

    private void jTextContratoActitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContratoActitudesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoActitudesActionPerformed

    private void jTextContratoActitudesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContratoActitudesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoActitudesKeyTyped

    private void jCmbContratoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbContratoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbContratoTipoActionPerformed

    private void jBtnBuscarAspirantes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarAspirantes1ActionPerformed
        listarAspirantes();
    }//GEN-LAST:event_jBtnBuscarAspirantes1ActionPerformed

    private void jTextContratoFechaInicioMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContratoFechaInicioMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaInicioMesActionPerformed

    private void jTextContratoFechaInicioMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContratoFechaInicioMesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaInicioMesKeyTyped

    private void jTextContratoFechaInicioAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContratoFechaInicioAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaInicioAnoActionPerformed

    private void jTextContratoFechaInicioAnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContratoFechaInicioAnoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaInicioAnoKeyTyped

    private void jTextContratoFechaInicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContratoFechaInicio3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaInicio3ActionPerformed

    private void jTextContratoFechaInicio3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContratoFechaInicio3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaInicio3KeyTyped

    private void jTextContratoFechaInicio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContratoFechaInicio4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaInicio4ActionPerformed

    private void jTextContratoFechaInicio4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContratoFechaInicio4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaInicio4KeyTyped

    private void jTextContratoFechaInicio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContratoFechaInicio5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaInicio5ActionPerformed

    private void jTextContratoFechaInicio5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContratoFechaInicio5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaInicio5KeyTyped

    private void jTextContratoFechaFinAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContratoFechaFinAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaFinAnoActionPerformed

    private void jTextContratoFechaFinAnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContratoFechaFinAnoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaFinAnoKeyTyped

    private void jTextContratoFechaFinMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContratoFechaFinMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaFinMesActionPerformed

    private void jTextContratoFechaFinMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContratoFechaFinMesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaFinMesKeyTyped

    private void jTextContratoFechaFinDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContratoFechaFinDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaFinDiaActionPerformed

    private void jTextContratoFechaFinDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContratoFechaFinDiaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContratoFechaFinDiaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContratarAspirante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContratarAspirante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContratarAspirante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContratarAspirante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContratarAspirante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAspirante;
    private javax.swing.ButtonGroup btnGrpCopiaCedula;
    private javax.swing.ButtonGroup btnGrpCopiaTitulo;
    private javax.swing.ButtonGroup btnGrpREvisionMedica;
    private javax.swing.ButtonGroup btnGrpSexo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jBtnBuscarAspirantes;
    private javax.swing.JButton jBtnBuscarAspirantes1;
    private javax.swing.JButton jBtnContratar;
    private javax.swing.JButton jBtnNuevoContrato;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jCmbContratoTipo;
    private javax.swing.JComboBox<String> jCmbContratoTipoEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAspirantesAptos;
    private javax.swing.JTextField jTextContratoActitudes;
    private javax.swing.JTextField jTextContratoAptitudes;
    private javax.swing.JTextField jTextContratoBanco;
    private javax.swing.JTextField jTextContratoCargo;
    private javax.swing.JTextField jTextContratoDepto;
    private javax.swing.JTextField jTextContratoFechaFinAno;
    private javax.swing.JTextField jTextContratoFechaFinDia;
    private javax.swing.JTextField jTextContratoFechaFinMes;
    private javax.swing.JTextField jTextContratoFechaInicio3;
    private javax.swing.JTextField jTextContratoFechaInicio4;
    private javax.swing.JTextField jTextContratoFechaInicio5;
    private javax.swing.JTextField jTextContratoFechaInicioAno;
    private javax.swing.JTextField jTextContratoFechaInicioDia;
    private javax.swing.JTextField jTextContratoFechaInicioMes;
    private javax.swing.JTextField jTextContratoNumCuenta;
    private javax.swing.JTextField jTextContratoPuntaje;
    private javax.swing.JTextField jTextContratoSueldo;
    private javax.swing.JRadioButton rdbtFemenino;
    private javax.swing.JRadioButton rdbtMasculino;
    // End of variables declaration//GEN-END:variables
}
